### ISSUE TITLE
Instructions on the Github page are wrong

### ISSUE THREAD

**Issue by blogcraft** [madoar/angular-archwizard#105]
The readme in the Github project won't work given the npm package that it asks to install `npm install --save ng2-archwizard` 
It appears that they are for a different Version that is not the one that is the current npm build. If there is an other version, it is NOT stated in the documentation.

For example, in the Github readme there is an `<aw-wizard`> tag and in the current version it is `<wizard>`

**Comment by madoar** [comment]
Yes you're right, Github contains the source code for `ng2-archwizard` version `3.0.0`, while npm contains only version `2.1.0`.
The reason being is that version `3.0.0` is still in development, and I didn't think about creating a new development branch for this.

**Comment by madoar** [comment]
I've just released version `3.0.0` of the library.
Version `3.0.0` is released under a new package name, named [angular-archwizard](https://www.npmjs.com/package/angular-archwizard).

The released version `3.0.0` is compatible with the README found on GitHub.
