### ISSUE TITLE
Support for changing the default navBarLayout (Other than a circle)

### ISSUE THREAD

**Issue by blogcraft** [madoar/angular-archwizard#106]
There should be a way to change the color and shape of the navBar items.

Example:
Default is the current circles.
Be able to change the shape to square or rounded square
Be able to change color scheme.
etc.

Also in phone size screens, being able to only show the current step. Maybe show an indicator of the previous and the next one but not more (for example if my wizzard has a lot of steps).

Thanks

**Comment by madoar** [comment]
The wizard will support custom navigation bar layouts starting with version `3.0.0`, which is currently in development.
It should be possible to change the circles to other shapes and to change the colors via custom css.

I don't understand your suggestion about phone size screens. Can you elaborate it a little bit more and provide a short image showing your suggestion?

In case you want to give version `3.0.0` a go you can do that by cloning the repository and building it yourself.
The documentation on github in the README file already contains the new syntax for version `3.0.0`.

**Comment by madoar** [comment]
I've just released version `3.0.0` of the library.
Version `3.0.0` is released under a new package name, named [angular-archwizard](https://www.npmjs.com/package/angular-archwizard).

An demo example using custom css can be found at https://github.com/madoar/angular-archwizard-demo/tree/master/src/app/custom-css and https://madoar.github.io/angular-archwizard-demo/#/custom-css

If you have any remaining questions, feel free to add a comment on this issue.
