### ISSUE TITLE
Previous button not working

### ISSUE THREAD

**Issue by gate3** [madoar/angular-archwizard#107]
Hi, thanks for this fine library. It's been performing well so far but I encountered a strange problem recently. I created a wizard with four steps, and everything works fine when i try to use previous and next buttons from step1 and step2. When i get to step3 it allows me go back to step2 but I cannot seem to access step1 any longer.

Here is the code for the wizard steps 

<div class="section-bodymain">
    <div class="container">
        <wizard #wizard [ngClass]="{'hidden-nav':!barStatus}"
                navBarLayout="large-filled-symbols"
                navBarLocation="top">
            <div class="col-xs-12 no-padding">

            <role-step wizardStep optionalStep (stepEnter)="scrollToTop($event)"
                  navigationSymbol="1" 
                  (selectedRole)="getSelectedRole($event)">
                <ng-template wizardStepTitle>
                    <div *ngIf="barStatus">
                        <h3>
                            {{'REGISTER.STEP_HEADING.ROLE.TITLE' | translate}}
                        </h3><br/>
                        <h4 class="small-title">
                            {{'REGISTER.STEP_HEADING.ROLE.DESCRIPTION' | translate}}
                        </h4>
                    </div>
                </ng-template>
            </role-step>
            <step1 wizardStep optionalStep (stepEnter)="scrollToTop($event)"
                  navigationSymbol="2" [wiz]="wizard">
                <ng-template wizardStepTitle>
                    <div *ngIf="barStatus">
                        <h3>
                            {{'REGISTER.STEP_HEADING.PERSONAL_DETAILS.TITLE' | translate}}
                        </h3><br/>
                        <h4 class="small-title">
                            {{'REGISTER.STEP_HEADING.PERSONAL_DETAILS.DESCRIPTION' | translate}}
                        </h4>
                    </div>
                </ng-template>
            </step1>
            <step2 wizardStep optionalStep (stepEnter)="scrollToTop($event)"
                   navigationSymbol="3" 
                   [showRole]="selectedRole">
                <ng-template wizardStepTitle>
                    <div *ngIf="barStatus">
                        <h3>
                            {{'REGISTER.STEP_HEADING.PROFESSIONAL_DETAILS.TITLE' | translate}} 
                        </h3><br/>
                        <h4 class="small-title">
                            {{'REGISTER.STEP_HEADING.PROFESSIONAL_DETAILS.DESCRIPTION' | translate}}
                        </h4>
                    </div>
                </ng-template>
            </step2>
            <step3 wizardStep navigationSymbol="4" 
                    (stepEnter)="scrollToTop($event)" 
                    [user]="selectedRole" 
                    (userDetails)="getThisUser($event)">
                <ng-template wizardStepTitle>
                    <div *ngIf="barStatus">
                        <h3>
                            {{'REGISTER.STEP_HEADING.PAYMENT_CONFIRMATION.TITLE' | translate}}
                        </h3><br/>
                        <h4 class="small-title">
                            {{'REGISTER.STEP_HEADING.PAYMENT_CONFIRMATION.DESCRIPTION' | translate}}
                        </h4>
                    </div>
                </ng-template>
            </step3>
            </div>
        </wizard>
    </div>    

Thanks in advance

**Comment by madoar** [comment]
The part of the code you're added to your issue looks good to me.

To better help you I would need a more complete code sample.
For example your sample is missing the beginning `<wizard ...>` tag.
In addition I don't know how you navigate between the steps.
Do you use the `nextStep` and `previousStep` directives, or do you use the `goToStep` directive, or do you use the navigation bar, or do you use some custom code?

**Comment by madoar** [comment]
If this question is still relevant/open, feel free to open a new issue.
