### ISSUE TITLE
How do you change the font of a certain step title?

### ISSUE THREAD

**Issue by omryha** [madoar/angular-archwizard#110]
I couldn't figure it out.

Thanks.

**Comment by madoar** [comment]
I'm just released version `3.0.0` of the library.
With it comes a new demo example, which illustrates how to use custom css.
The example can be found at: https://github.com/madoar/angular-archwizard-demo/tree/master/src/app/custom-css and https://madoar.github.io/angular-archwizard-demo/#/custom-css

If you have any open questions feel free to add a comment.

**Comment by omryha** [comment]
Hi,

Thanks for the respond.

I tried to implement my CSS on the `aw-wizard` element but it did not work:

Attached below is my CSS file, that is found in the same component using the Wizard.

**myNavBar** is the name of the class that should be added to the element so it attributes will change.
What am I doing wrong?

Thanks,

Omry

-------------------------------------------------------------------------------
**componentStyle.css**

`aw-wizard-navigation-bar.myNavBar ul.steps-indicator {
    padding: 60px 0 10px 0!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li:not(:last-child):before {
    background-color: #E6E6E6!important;
    content: ''!important;
    position: absolute!important;
    height: 1px!important;
    width: calc(100% - 50px)!important;
    top: -25px!important;
    left: calc(50% + 25px)!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li:after {
    position: absolute!important;
    top: -50px!important;
    left: calc(50% - 25px)!important;
    width: 50px!important;
    height: 50px!important;
    content: ''!important;
    text-align: center!important;
    vertical-align: middle!important;
    line-height: 50px!important;
    transition: 0.25s!important;
    border-radius: 100%!important;
    background-color: #E6E6E6!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li.default a:hover {
    color: #808080!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li.current:after {
    background-color: #808080!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li.done:after {
    background-color: #339933!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li.optional:after {
    background-color: #38ef38!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li.editing:after {
    background-color: #263c4a !important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator {
    padding: 60px 0 10px 0!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li:not(:last-child):before {
    background-color: #E6E6E6!important;
    content: ''!important;
    position: absolute!important;
    height: 1px!important;
    width: calc(100% - 50px)!important;
    top: -25px!important;
    left: calc(50% + 25px)!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li:after {
    position: absolute!important;
    top: -50px!important;
    left: calc(50% - 25px)!important;
    width: 50px!important;
    height: 50px!important;
    content: ''!important;
    text-align: center!important;
    vertical-align: middle!important;
    line-height: 50px!important;
    transition: 0.25s!important;
    border-radius: 100%!important;
    background-color: #E6E6E6!important;
    color: black!important;
    content: attr(step-symbol)!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li.default a:hover {
    color: greenyellow !important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li.current:after {
    background-color: pink !important;
    color: black!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li.done:after {
    background-color: purple !important;
    color: black!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li.optional:after {
    background-color: cyan !important;
    color: black!important;
}

aw-wizard-navigation-bar.myNavBar ul.steps-indicator li.editing:after {
    background-color: #263c4a !important;
    color: black!important;
}`

**Comment by madoar** [comment]
On a single look I would say your selectors are wrong.
The css class `myNavBar` is not a part of `aw-wizard-navigation-bar`, but of `aw-wizard`, i.e. you'll need to change your selectors to for example:
```css
...
.myNavBar aw-wizard-navigation-bar ul.steps-indicator li.editing:after {
    background-color: #263c4a !important;
    color: black!important;
}
```

If this doesn't help I need a more complete snipped, i.e. ideally the ts, html and css file of your component.

**Comment by omryha** [comment]
Thank you for answering.

This is the HTML file of the component:

```
<div class="container height100">
    <h1 class="arimo heading1 dark-blue-txt bold enrollHeading1">TEXT TEXT TEXT</h1>
    <div class="raNavBar">
        <aw-wizard navBarLayout="large-filled-symbols" navBarLocation="top" navBarDirection="left-to-right">
            <aw-wizard-step [stepTitle]="stepTitles[0]" [navigationSymbol]="{ symbol: '1', fontFamily: 'Arimo' }">
                <div class="wrap-step lg-mt-40 ">
                    <app-step1></app-step1>
                    <hr class="enrollHorizontal">
                </div>
                <button type="button" class="btn blue white-txt arimo" awNextStep>TEXT TEXT TEXT</button>
            </aw-wizard-step>
            <aw-wizard-step [stepTitle]="stepTitles[1]" optionalStep [navigationSymbol]="{ symbol: '2', fontFamily: 'Arimo' }">
                <div class="wrap-step lg-mt-40 ">
                    <app-step2></app-step2>
                    <hr class="enrollHorizontal">
                </div>
                <button type="button" class="btn previous blue white-txt arimo" awPreviousStep>TEXT TEXT TEXT</button>
                <button type="button" class="btn blue white-txt arimo" awNextStep>המשך</button>
            </aw-wizard-step>
            <aw-wizard-step [stepTitle]="stepTitles[2]" optionalStep [navigationSymbol]="{ symbol: '3', fontFamily: 'Arimo' }">
                <div class="wrap-step lg-mt-40 ">
                    <app-step3></app-step3>
                    <hr class="enrollHorizontal">
                </div>
                <button type="button" class="btn previous blue white-txt arimo" awPreviousStep>TEXT TEXT TEXT</button>
                <button type="button" class="btn blue white-txt arimo" awNextStep>המשך</button>
            </aw-wizard-step>
            <aw-wizard-step [stepTitle]="stepTitles[3]" optionalStep [navigationSymbol]="{ symbol: '4', fontFamily: 'Arimo' }">
                <div class="wrap-step lg-mt-40 ">
                    <app-step4></app-step4>
                    <hr class="enrollHorizontal">
                </div>
                <button type="button" class="btn previous blue white-txt arimo" awPreviousStep>TEXT TEXT TEXT</button>
                <button type="button" class="btn blue white-txt arimo" awNextStep>המשך</button>
            </aw-wizard-step>
            <aw-wizard-completion-step [stepTitle]="stepTitles[4]" [navigationSymbol]="{ symbol: '5', fontFamily: 'Arimo' }">
                <div class="wrap-step lg-mt-40 ">
                    <app-step5></app-step5>
                    <hr class="enrollHorizontal">
                </div>
                <button type="button" class="btn previous blue white-txt arimo" awPreviousStep>TEXT TEXT TEXT</button>
                <button type="button" class="btn blue white-txt arimo" awNextStep>סיום</button>
            </aw-wizard-completion-step>
        </aw-wizard>
    </div>
</div>
```

And this is the CSS file:

```
aw-wizard-step,
aw-wizard-completion-step {
    position: relative!important;
    height: 80%!important;
}

aw-wizard-step button {
    position: relative!important;
    bottom: 0!important;
    right: 80%!important;
}

aw-wizard-completion-step button {
    position: relative;
    bottom: 0;
    right: 80%;
}

.enrollHeading1 {
    margin: 40px 0px 40px 0px;
}

.enrollHorizontal {
    margin-top: 10px;
    border: 1px solid #efefef;
}


/***STEPPER STYLING***/

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.editing:after {
    background-color: #263c4a !important;
    color: black!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator {
    padding: 60px 0 10px 0!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li:not(:last-child):before {
    background-color: #E6E6E6!important;
    content: ''!important;
    position: absolute!important;
    height: 1px!important;
    width: calc(100% - 50px)!important;
    top: -25px!important;
    left: calc(50% + 25px)!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li:after {
    position: absolute!important;
    top: -50px!important;
    left: calc(50% - 25px)!important;
    width: 50px!important;
    height: 50px!important;
    content: ''!important;
    text-align: center!important;
    vertical-align: middle!important;
    line-height: 50px!important;
    transition: 0.25s!important;
    border-radius: 100%!important;
    background-color: #E6E6E6!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.default a:hover {
    color: #808080!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.current:after {
    background-color: #808080!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.done:after {
    background-color: #339933!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.optional:after {
    background-color: #38ef38!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.editing:after {
    background-color: #263c4a !important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator {
    padding: 60px 0 10px 0!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li:not(:last-child):before {
    background-color: #E6E6E6!important;
    content: ''!important;
    position: absolute!important;
    height: 1px!important;
    width: calc(100% - 50px)!important;
    top: -25px!important;
    left: calc(50% + 25px)!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li:after {
    position: absolute!important;
    top: -50px!important;
    left: calc(50% - 25px)!important;
    width: 50px!important;
    height: 50px!important;
    content: ''!important;
    text-align: center!important;
    vertical-align: middle!important;
    line-height: 50px!important;
    transition: 0.25s!important;
    border-radius: 100%!important;
    background-color: #E6E6E6!important;
    color: black!important;
    content: attr(step-symbol)!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.default a:hover {
    color: greenyellow !important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.current:after {
    background-color: pink !important;
    color: black!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.done:after {
    background-color: purple !important;
    color: black!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.optional:after {
    background-color: cyan !important;
    color: black!important;
}

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.editing:after {
    background-color: #263c4a !important;
    color: black!important;
}
```

**Comment by madoar** [comment]
Did you add `encapsulation: ViewEncapsulation.None` to your component?
Is the custom css partially applied, or not at all? (What part exactly doesn't work of your custom css)

I think you can remove the line `<div class="raNavBar">` and add the css class directly to the wizard, i.e.:
```html
<aw-wizard class="raNavBar" navBarLayout="large-filled-symbols" navBarLocation="top" navBarDirection="left-to-right">
```

**Comment by madoar** [comment]
In addition please be aware, that you're using some redundant and contrary css selectors.
For example:
```css
.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.current:after {
    background-color: #808080!important;
}

and

.raNavBar aw-wizard-navigation-bar ul.steps-indicator li.current:after {
    background-color: pink !important;
    color: black!important;
}
```

**Comment by omryha** [comment]
Thanks a lot, much appreciated!

**Comment by madoar** [comment]
Nice to hear I could help :)
