### ISSUE TITLE
Ionic 2 Support

### ISSUE THREAD

**Issue by 009topersky** [madoar/angular-archwizard#115]
Good day!

The Wizard is very awesome

I just want to know if this module is capable to use on Mobile Ionic 2

**Comment by nabwill** [comment]
How I import angular-archwizard in ionic 2+ project? @madoar, you got it?

**Comment by 009topersky** [comment]
Good day!

i used this component on my ionic 2 project

its just the same as on how you import the angular-archwizard on your angular 4/5/6 Project

Thumbs up on this library (Y)

thank @madoar !
