### ISSUE TITLE
I am unable to get anything to appear in the large empty symbol circles like a number.

### ISSUE THREAD

**Issue by supermoore1025** [madoar/angular-archwizard#121]
Here is my html

**<aw-wizard **navBarLayout** ="large-empty-symbols">
            <aw-wizard-step stepTitle="Title of step 1" [navigationSymbol]="{ symbol: '1' }">
              Content of Step 1
              <button type="button" awNextStep>Next Step</button>
              <button type="button" [awGoToStep]="{stepIndex: 2}">Go directly to third Step</button>
            </aw-wizard-step>
            <aw-wizard-step stepTitle="Title of step 2" [navigationSymbol]="{ symbol: '2' }">
              Content of Step 2
              <button type="button" awPreviousStep>Go to previous step</button>
              <button type="button" awNextStep>Go to next step</button>
            </aw-wizard-step>
            <aw-wizard-step stepTitle="Title of step 3" [navigationSymbol]="{ symbol: '3' }">
              Content of Step 3
              <button type="button" awPreviousStep>Previous Step</button>
              <button type="button" (click)="finishFunction()">Finish</button>
            </aw-wizard-step>
 </aw-**wizard**>**

**Comment by madoar** [comment]
Your code seems to be missing the end tags and the button tags for the next and previous buttons.

Have you tried building the demo application at https://github.com/madoar/angular-archwizard-demo?
This application provides an example for the navigation symbols at https://github.com/madoar/angular-archwizard-demo/tree/master/src/app/large-empty-symbols

**Comment by tyaginboston** [comment]
Same Issue here. none of the Layout option works. i installed the Archwizard. Copy the code in page template. works fine with default setting, all other settings takes away the circle.

**Comment by madoar** [comment]
@tyaginboston can you please provide a short code snipped, which produces the effect you've described, and a screenshot showing the effect?
In addition it would be helpful to know which version of angular-archwizard and angular you're using.

**Comment by madoar** [comment]
@tyaginboston your problem seems to be the input parameter `navBarLayout`.
When using `[navBarLayout]` angular expects a javascript/typescript expression.
The problem with your expression `large-filled-symbols` is, that it is not a string and neither an existing variable.

To get it working, you can use one of the following lines:
- `<aw-wizard [navBarLayout]="'large-filled-symbols'">`
- `<aw-wizard navBarLayout="large-filled-symbols">`

**Comment by madoar** [comment]
If this question is still relevant/open, feel free to open a new issue.
