### ISSUE TITLE
mark the step with 'success', 'warning' icons

### ISSUE THREAD

**Issue by balakrishnarudraraju** [madoar/angular-archwizard#122]
Thanks for sharing your good work, it is really useful.

Have a request for new feature may be, 
is it possible to highlight the step-indicator (in large filled with symbol) by placing a 'tick' or 'warning' symbol beside to it to highlight that the particular step has valid values or warnings to be resolved?

**Comment by madoar** [comment]
With the current version of `angular-archwizard` it is possible to customize the step indicator more extensively through the use of a `ng-template` component with the `[awWizardStepSymbol]` directive. By using this directive you can set the content inside the step indicator freely which should allow you to define a symbol if certain conditions are fulfilled (or not fulfilled).
