### ISSUE TITLE
Angular 6 + AOT + lazy-loaded: Dependency injection fails

### ISSUE THREAD

**Issue by guillaumegarcia13** [madoar/angular-archwizard#123]
I recently migrated to Angular 6 and when **AOT-compiling** a **lazy-loaded module** which imports ArchwizardModule, the dependecy injection fails, meaning:

`@ViewChild(WizardComponent) public wizard: WizardComponent;`

and then calling

`this.wizard.navigation.goToNextStep();`

it fails because this.wizard is _undefined_.

I usually use this to programmatically change the step of the wizard.
Nonetheless, if I use the **more simple approach** with awNextStep directive, it **works as expected**.

Thanks in advance for your insights!

**Comment by madoar** [comment]
This seems to be the same issue as in #116.

The issue seems to be that `@ViewChild` doesn't seem to do its job in this case as intended.
Can you check, if `@ViewChild` works, when used with other libraries?

**Comment by guillaumegarcia13** [comment]
Indeed!
I'm closing this one then as it is a duplicate.

**Comment by CNaiko** [comment]
@madoar have you got some ideas that why can not inject like this in AOT?

**Comment by madoar** [comment]
No currently I have no idea.
My problem is, that I'm not facing this error, which makes it hard for me to debug.

The interesting thing is, that you receive no error (exception) message, just an `undefined` value when you access the injected object.
