### ISSUE TITLE
Error: Metadata version mismatch

### ISSUE THREAD

**Issue by artemvalmus** [madoar/angular-archwizard#127]
When running ng serve:

`Error: Metadata version mismatch for module C:/project/node_modules/angular-archwizard/angular-archwizard.d.ts, found version 4, expected 3`

ng --version:
```
@angular/cli: 1.4.9
node: 6.11.1
os: win32 x64
@angular/animations: 4.4.7
@angular/common: 4.4.7
@angular/compiler: 4.4.7
@angular/compiler-cli: 4.3.1
@angular/core: 4.4.7
@angular/forms: 4.3.1
@angular/http: 4.4.7
@angular/platform-browser: 4.4.7
@angular/platform-browser-dynamic: 4.4.7
@angular/platform-server: 4.1.3
@angular/router: 4.4.7
@angular/cli: 1.4.9
@angular/language-service: 4.4.7
typescript: 2.3.4
```

The funniest thing is that it worked yesterday.

**Comment by artemvalmus** [comment]
**"version":4** is specified in the **angular-archwizard.metadata.json** file. Why is that? Changing it to **"version":3** solves the problem.

**Comment by madoar** [comment]
The reason for the error message is, that you're using `angular-archwizard` version `3.0.0` together with Angular 4.

Starting with `angular-archwizard` version `3.0.0`, I've switched the gulp build script to `ng-packagr`.
The built, created by `ng-packagr`, is only compatible with Angular 5+.

If you want to use `angular-archwizard` together with Angular 4 you must use version `2.1.0`, which you can get at https://www.npmjs.com/package/ng2-archwizard.
Please be aware, that version `2.1.0` doesn't contain all features of version `3.0.0` and its syntax differs a little bit.

**Comment by artemvalmus** [comment]
Got it, thanks.
