### ISSUE TITLE
How initialize step to 'x' index

### ISSUE THREAD

**Issue by igioya** [madoar/angular-archwizard#128]
Hi @madoar, how are you?
I wanted set the default index but can't do work it.
So, i think about initialize the state of navigation to free, to can go to step x when initialize my component. The problem is that I can't change state of navigation to free.
I tried this.wizard.navigationMode = 'free', but i dont know if that is correctly. And not working.
Can you help me?
Thank you!

P.D: The directive [navigationMode] not working. The [defaultStepIndex] set the object property but is not reflected in the view. 
Thanks!!

**Comment by madoar** [comment]
How do you instantiate your wizard component, i.e. what html code do you use?
Can you provide a short code snippet?

**Comment by madoar** [comment]
If this question is still relevant/open, feel free to open a new issue.
