### ISSUE TITLE
navigationSymbol.fontFamily should only apply to the symbol, not step title text

### ISSUE THREAD

**Issue by earshinov** [madoar/angular-archwizard#130]
The issue can be seen in angular-archwizard-demo (https://github.com/madoar/angular-archwizard-demo/tree/master/src/app/custom-step-symbol)

custom symbol step (take notice of the text):
![custom symbol step](https://user-images.githubusercontent.com/52021/42137922-76981920-7d7d-11e8-9053-43edaf7fc073.png)

usual step:
![usual step](https://user-images.githubusercontent.com/52021/42137924-795167b6-7d7d-11e8-854e-1f3bfcd7a66f.png)

devtools:
![devtools](https://user-images.githubusercontent.com/52021/42137926-7cf5b340-7d7d-11e8-9a61-1b22acf9f0de.png)

**Comment by madoar** [comment]
I've just released `angular-archwizard` version `4.0.0` to [npm](https://www.npmjs.com/package/angular-archwizard)! Version `4.0.0` should fix this issue. Feel free to give it a try!
