### ISSUE TITLE
Vertical alignment of symbols inside step indicators is incorrect in the absence of bootstrap CSS

### ISSUE THREAD

**Issue by earshinov** [madoar/angular-archwizard#137]
Demo:

![without bootstrap](https://user-images.githubusercontent.com/52021/43265316-0fe24070-90f1-11e8-9d35-f2d835ca0b0f.png)

Compare w/ the case when bootstrap CSS is included:

![with bootstrap](https://user-images.githubusercontent.com/52021/43265418-59873258-90f1-11e8-8117-173617172673.png)

The problem is that the selector in

```
/* --- http://www.paulirish.com/2012/box-sizing-border-box-ftw/ ---- */
* {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```

in `wizard-navigation-bar.component.horizontal.less` and `wizard-navigation-bar.component.vertical.less` does not apply to `:before` and `:after` pseudo-elements. Instead, the selector should be

```
*, *:before, *:after
```

as in Bootstrap CSS.

**Comment by madoar** [comment]
Fixed in current develop branch
