### ISSUE TITLE
Programmaticaly change step

### ISSUE THREAD

**Issue by darge98** [madoar/angular-archwizard#138]
Hi,

I want to know if it's possible to go to the previous/next step in my component after a specific function.

Thanks

**Comment by madoar** [comment]
There are multiple ways to change the step to the next/previous step.

The question is, how do you trigger your function?
The easiest way is to use one of the provided directives (for example `[awNextStep]` or `[awPreviousStep]`) by `angular-archwizard`.

Alternatively you can use the internal API.
For this you'll need to inject the `WizardComponent` and then call `wizard.navigation.(goToNextStep()/goToPreviousStep())`.

**Comment by fel-cesar** [comment]
Searched the whole StackOverflow and just found it here 💛

**Comment by darge98** [comment]
There's also an event where i can subscribe to detect when navigation change?

**Comment by madoar** [comment]
What do you mean with navigation change?

**Comment by rajitgola** [comment]
Any update on this? I want to programmatically change to next step in my .ts file

**Comment by guillaumegarcia13** [comment]
madoar wrote:
> lternatively you can use the internal API.
> For this you'll need to inject the WizardComponent and then call wizard.navigation.(goToNextStep()/goToPreviousStep()).

Does not answer your question, @rajitgola?

**Comment by darge98** [comment]
@madoar i want to detect every time i change my active step, like an a subscription to this event

**Comment by fhidal01** [comment]
@madoar or guillaumegarcia13 can you provide and code example of what you mean?

I am getting the following error:

core.js:1601 ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[BudgetComponent -> WizardComponent]: 
  StaticInjectorError(Platform: core)[BudgetComponent -> WizardComponent]: 
    NullInjectorError: No provider for WizardComponent!
Error: StaticInjectorError(AppModule)[BudgetComponent -> WizardComponent]: 
  StaticInjectorError(Platform: core)[BudgetComponent -> WizardComponent]: 
    NullInjectorError: No provider for WizardComponent!


with the following code:

import { WizardComponent } from "angular-archwizard";

export class SampleComp {
    
constructor(
        private test: WizardComponent
    ) { }

    testing() {
        this.test.navigation.goToStep(2);
    }
}

**Comment by fhidal01** [comment]
NVM i was able to get it working by referring to question #17

**Comment by madoar** [comment]
@darge98 there is no single point where you can add such a listener currently.
Currently, you can receive an event at every wizard step whenever you enter or exit the step.
For this you need to bind a function to the `(stepEnter)` and `(stepExit)` output of the wizard steps you're interested in.

@fhidal01 yes, the injection part is missing in my previous comment.
You also need to inject the WizardComponent like the following:
```typescript
@ViewChild(WizardComponent)
public wizard: WizardComponent;
```
