### ISSUE TITLE
Scroll after step opened

### ISSUE THREAD

**Issue by panagulis72** [madoar/angular-archwizard#139]
Hi, I want that when the user click on the title of a step, the view scroll until the new-opened step. I have a vertical scroll.  
This is the html code:
` <aw-wizard-step (stepEnter)="onInfoEnter(generalInfo)" stepId="generalInfo" id="generalInfo" #generalInfo [navigationSymbol]="{ symbol: '&#xf00c;', fontFamily: 'FontAwesome' }">`

This is the .ts code:
`  onInfoEnter(test: any) {
    let targetElement = document.getElementById(test.stepId);
    targetElement.scrollIntoView();
  }`

but it doesn't scroll, and there are no error. I also tried with this:

`  onInfoEnter(test: any) {
    let targetElement = document.getElementById(test.stepId);
    this.currentComponent.nativeElement.scrollTo(0, targetElement.offsetTop, 500);
  }`

but it doesn't work yet! Any suggestion?

**Comment by madoar** [comment]
Yes, you're right about that.
The wizard currently doesn't scroll to the current step.

About your code:
Your html code contains the following statement: `(stepEnter)="onInfoEnter(generalInfo)"`
How is `generalInfo`, which you're passing to `onInfoEnter` defined?

**Comment by conradolk** [comment]
You should scroll to a <div #id or id="stepId"> element, not the aw-wizard-step.

**Comment by madoar** [comment]
@conradolk do you want to provide an example for this in the demo repository?

**Comment by madoar** [comment]
I think this issue should be solved outside of the `angular-archwizard` codebase (like @conradolk mentioned)
