### ISSUE TITLE
[Question] - Aproach steps x components

### ISSUE THREAD

**Issue by nabwill** [madoar/angular-archwizard#141]
Modoar, is recommended work with contents steps like way:

```

  <aw-wizard>
    <aw-wizard-step stepTitle="step1">
      <page-comp1></page-comp1>
    </aw-wizard-step>
  <aw-wizard-step stepTitle="step2">
      <page-comp2></page-comp2>
    </aw-wizard-step>
    <aw-wizard-step stepTitle="step3">
      <page-comp3></page-comp3>
    </aw-wizard-step>
  </aw-wizard>
```

**Comment by madoar** [comment]
This is one way to work with the wizard.
If you only want to add a single component to every wizard step, I would suggest you use the `awWizardStep` directive for your components.
An example how this is done is shown at https://github.com/madoar/angular-archwizard-demo/tree/master/src/app/wizard-step-directives

**Comment by madoar** [comment]
If this question is still relevant/open, feel free to open a new issue.
