### ISSUE TITLE
Minor documentation typo

### ISSUE THREAD

**Issue by earshinov** [madoar/angular-archwizard#145]
https://github.com/madoar/angular-archwizard/blame/master/README.md#L281

> Be aware, that you can only use `[awWizardStepTitle]` together with Angular, because `ng-template` was introduced in Angular 4.

Should probably be:

Be aware, that you can only use `[awWizardStepTitle]` together with Angular **4 or later**, because `ng-template` was introduced in Angular 4.

**Comment by madoar** [comment]
Yes you're right

**Comment by adekoder** [comment]
Sent in a PR for this issue
