### ISSUE TITLE
[navigationSymbol] documentation

### ISSUE THREAD

**Issue by vicoysito** [madoar/angular-archwizard#151]
Hello @madoar ,  I've realized a problem with the documentation on [navigationSymbol], you have missed a comma  on the code, between symbol and fontFamily. `<aw-wizard-step stepTitle="Second Step" [navigationSymbol]="{ symbol: '&#xf2dd;' ,  fontFamily: 'FontAwesome' }"></aw-wizard-step>` . Could you please add it.

Thanks!

**Comment by mpintener** [comment]
Did you try using different icons based on a condition in every step ?
