### ISSUE TITLE
Steps disappears and lost stepIndex

### ISSUE THREAD

**Issue by manuelabarca** [madoar/angular-archwizard#153]
EN: I am creating a dynamic wizard, which is showing four steps, when entering new elements to the array of stages and pressing the "next" button, the following stages disappear, because the "stepIndex" is lost and the class remains "hidden" in the steps

ES: Estoy creando un wizard dinamico, el cual va mostrando de a cuatro pasos, al momento de ingresar nuevos elementos al array de las etapas y presionar el boton "siguiente", las siguientes etapas desaparecen, porque se pierde el "stepIndex" y queda la clase "hidden" en las etapas

**App.component.html**
`<aw-wizard #wizard>
	<aw-wizard-step  [stepTitle]="wizard.header" *ngFor="let wizard of (tempWizard | slice:tempWizard.length-4); let first = first; let last = last; let i = index">
		<div class="centered-content">
			{{wizard.content}}
			<br /><br />

			<div class="btn-group">
				<button class="btn btn-secondary" awPreviousStep *ngIf="!first">Anterior</button>
        <button class="btn btn-secondary" awNextStep *ngIf="tempWizard.length != wizardSteps.length || !last" (click)="prueba(i,first, last, wizard)">Siguiente</button>
        <button class="btn btn-secondary" *ngIf="tempWizard.length == wizardSteps.length && last">Finalizar</button>
			</div>
		</div>
	</aw-wizard-step>
</aw-wizard>`

**App.component.ts**
`import { Component, ChangeDetectorRef, ViewChild } from '@angular/core';
import { WizardComponent } from 'angular-archwizard';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @ViewChild(WizardComponent) public wizard: WizardComponent;
  title = 'pruebas';
  wizardSteps: Array<Object>;
  tempWizard = [];
  next;
  paseUnaVez = false;
  lastStep = 0;
  constructor(private _changeDetectionRef: ChangeDetectorRef) {

    this.wizardSteps = [
      {
        header: 'Steptitle 1',
        content: 'Content: Step 1',
        stepId: 1
      },
      {
        header: 'Steptitle 2',
        content: 'Content: Step 2',
        stepId: 2
      },
      {
        header: 'Steptitle 3',
        content: 'Content: Step 3',
        stepId: 3
      },
      {
        header: 'Steptitle 4',
        content: 'Content: Step 4',
        stepId: 4
      },
      {
        header: 'Steptitle 5',
        content: 'Content: Step 5',
        stepId: 5
      },
      {
        header: 'Steptitle 6',
        content: 'Content: Step 6',
        stepId: 6
      },
      {
        header: 'Steptitle 7',
        content: 'Content: Step 7',
        stepId: 7
      },
      {
        header: 'Steptitle 8',
        content: 'Content: Step 8',
        stepId: 8
      },
      {
        header: 'Steptitle 9',
        content: 'Content: Step 9',
        stepId: 9
      }
    ];

    for (let x = 0; x < 4; x++) {
      console.log("pase")
      this.tempWizard.push(this.wizardSteps[x])
    }

    this.lastStep = this.tempWizard[this.tempWizard.length - 1].stepId;
    console.log(this.tempWizard)
    
  }

  ngAfterViewInit(): void {
    this._changeDetectionRef.detectChanges();

  }

  prueba(i, first, last, wizard) {

    console.log(wizard.stepId)

    console.log(this.lastStep)

    var cont = 0;
    if (wizard.stepId == this.lastStep && this.tempWizard.length != this.wizardSteps.length) {
      console.log("Marca")
      for (let x = wizard.stepId; x < this.wizardSteps.length; x++) {
        if (cont == 4) {
          console.log(this.tempWizard)
          this.lastStep = this.tempWizard[this.tempWizard.length - 1].stepId;
          
          return;
        } else {
          cont++;
          this.paseUnaVez = true;
          this.tempWizard.push(this.wizardSteps[x])

        }
       
      }

    }

  }
}
`

![stei](https://user-images.githubusercontent.com/20046746/46710048-b1446400-cc1c-11e8-91d0-17f7a1a6dc77.png)
![stei2](https://user-images.githubusercontent.com/20046746/46710049-b1446400-cc1c-11e8-87a8-8ad070039d74.png)
![stei3](https://user-images.githubusercontent.com/20046746/46710050-b1446400-cc1c-11e8-9508-20b7f1dcf1c0.png)
I need help please or ideas. Thanks.

**Comment by madoar** [comment]
Sorry for my late answer.
It's kind of hard to read your code, because of the used code environment.
It would be useful to add all code to a code environment

About your issue:
Please try to reference the wizard by its id in the `@ViewChild` decorator, like the following:
```typescript
@ViewChild('wizard') public wizard: WizardComponent;
```
instead of:
```typescript
@ViewChild(WizardComponent) public wizard: WizardComponent;
```

**Comment by madoar** [comment]
I've just released version `4.0.0` of `angular-archwizard`. If this is still an issue with version `4.0.0` feel free to open a new issue.

**Comment by fbellod1986** [comment]
Hello guys, i have 4 steps, how i can go to the last step from step 1? help [awGoToStep]="{stepIndex: 3}" doesnt work :-(

**Comment by madoar** [comment]
@fbellod1986 how have you defined your wizard?
To allow for a free navigation you need to use the `free` navigation mode, otherwise you can set the steps in-between your first and your last step to optional
