### ISSUE TITLE
Problem with [canExit] when pass form.valid

### ISSUE THREAD

**Issue by GetTaxSolutions** [madoar/angular-archwizard#160]
Hello, I'm using <aw-wizard-step [canExit]="exitValidation(forms.get('service'))" ...> where forms.get('service') returns FormGroup object. In exitValidation method just return form.valid: 

> exitValidation(form): boolean {
>      return form ? form.valid : false;
>   }

When render it into the browser it show follow error:
```
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'canExit: true'. Current value: 'canExit: false'.
    at viewDebugError (core.js:7892)
    at expressionChangedAfterItHasBeenCheckedError (core.js:7880)
    at checkBindingNoChanges (core.js:7982)
    at checkNoChangesNodeInline (core.js:10847)
    at checkNoChangesNode (core.js:10832)
    at debugCheckNoChangesNode (core.js:11435)
    at debugCheckDirectivesFn (core.js:11363)
    at Object.eval [as updateDirectives]
```

There is problem when I'm using canExit and return form.valid. If return just true or false this error is not happens.

**Comment by madoar** [comment]
I don't think, that this is a problem with the wizard, but with the lifecycle phase in which form.valid is changed.
Can you try assigning a function to the `[canExit]` input, i.e. something like this:

```
exitValidation(form): (MovingDirection) => boolean {
   return (direction) => {
      return form ? form.valid : false;
   };
}
```

**Comment by GetTaxSolutions** [comment]
With function the message disappear. Looks like that work properly.
