### ISSUE TITLE
[navigationSymbol] and [stepTitle] - Enhancement

### ISSUE THREAD

**Issue by chelaruc** [madoar/angular-archwizard#162]
Hello there,

Thank you for this nice AngularJS plugin.
It is really cool and I have been using it in some of my projects.
I do have a question though.
Wouldn't it be nice if instead of passing the Unicode of an icon and its font family you would be able to pass its class name? 
This way, for icon libraries that do not show the Unicode, like Font Awesome library, you would not have to inspect each icon to get it's Unicode.
Also, it would be really nice to be able to send in the `[stepTitle]` some `HTML`. This way you could **bold** the title, or make an h1 title and so on. It would be a bit more practically.
Maybe it would be nice instead of having `[navigationSymbol]` and `[stepTitle]`as props, like Angluar components, the same way `<aw-wizard-step>` was done. Something like:
```
<aw-wizard-step>
    <aw-wizard-step-symbol>...</aw-wizard-step-symbol>
    <aw-wizard-step-title>
         ...some HTML
    </aw-wizard-step-title>
    <aw-wizard-step-content>
         .... contet here
    </aw-wizard-step-content>
</aw-wizard-step>
```
Anyway, this was just a tought. I found it a bit difficult working with some other icon libraries because I've always had to first create an `i` tag with the class for the icon I wanted and after that, inspect that element and take the icons Unicode.
Keep up the good work.

Best Regards,
Ciprian

**Comment by madoar** [comment]
There is already a directive you can use to define the step title more freely with custom html.
For more example how to do this take a look at https://github.com/madoar/angular-archwizard#awwizardsteptitle, https://github.com/madoar/angular-archwizard-demo/blob/master/src/app/custom-step-titles/custom-step-titles.component.html and https://madoar.github.io/angular-archwizard-demo/#/custom-step-titles.

In the currently released version of `angular-archwizard` it is not possible to specify the navigation symbol in html, but the currently developed version of `angular-archwizard` will support this.
You can take a look at the documentation of the new features on the `develop` branch in this repository.
In addition, you can find a demo showcasing the new features on the `develop` branch in the demo repository.
