### ISSUE TITLE
init step on enter

### ISSUE THREAD

**Issue by omidpaydar** [madoar/angular-archwizard#164]
hi
we have many widget wizard on dashboard and we want to dont init all step in init dashboard page.
we want init step on enter and destroy on finalize wizard.
- each step has input data that complete from before step.
tnx

**Comment by madoar** [comment]
I don't understand what you want to do.
Can you provide a short example?

**Comment by madoar** [comment]
I'll close this issue for now. If you still have the same problem feel free to open a new issue.
