### ISSUE TITLE
archwizard angular 6 

### ISSUE THREAD

**Issue by dridi93** [madoar/angular-archwizard#167]
Hi,
I have problem with this package with angular 6..
Error: "Template parse errors: aw-wizard-step' is not a known element:"

![capture du 2018-10-25 15-29-51](https://user-images.githubusercontent.com/11330682/47507829-dd8df080-d86a-11e8-8b1b-42ef1a27f01c.png)

**Comment by madoar** [comment]
Which version of `angular-archwizard` are you using?
Can you provide a code example producing the error?

**Comment by dridi93** [comment]
Version: "angular-archwizard": "^3.0.0"
`<aw-wizard>
<aw-wizard-step stepTitle="Title of step 1">
      Content of Step 1
      <ion-button awNextStep>Next</ion-button>
    </aw-wizard-step>
      Content of Step 2
      <ion-button awPreviousStep>Previous Step</ion-button>
      <ion-button (click)="finishFunction()">Finish</ion-button>
    </aw-wizard-step>
  </aw-wizard>`

**Comment by madoar** [comment]
I can't discover an error in your code snippet.
Have you tried to build and run the demo application?

**Comment by dridi93** [comment]
Hi @madoar 
Thanks for yor comment, i fixed the problem

**Comment by dridi93** [comment]
I have another question please,
How can'i use [navigationSymbol] with Ionicons ?

**Comment by madoar** [comment]
If you have a separate question it is better to open a new issue for it.

About your new question:
I'm not sure how you normally use Ionicons.
If you can use them via a unicode symbol you can use it the same way as shown in the README file.
If a html element is required to use an Ionicon, you will need to use the current development version (see #149).
This version has not been released yet.
Therefore to use it you will either need to build it yourself or wait until it has been released.

**Comment by dridi93** [comment]
Sorry about the second question in same issue,
For html element feature...KEEP WAITING :muscle: :muscle: :clock12:
Thanks.

**Comment by madoar** [comment]
I've just released `angular-archwizard` version `4.0.0` to [npm](https://www.npmjs.com/package/angular-archwizard)! Feel free to give it a try!
