### ISSUE TITLE
Using angular-archwizard as a progress preview

### ISSUE THREAD

**Issue by sebiglesias** [madoar/angular-archwizard#170]
Hello, firstly, I really love your angular-wizard!

I wanted to ask you about a way I want to use you wizard. It is not exactly as a wizard, but as a progress' state preview, like the following picture shows: 

<img width="1231" alt="screen shot 2018-11-08 at 23 02 20" src="https://user-images.githubusercontent.com/13668861/48238629-639d5180-e3aa-11e8-9eb9-e5a19311a3e8.png">

How can I tell the 'wizard', that the previous steps of the one selected are completed?

Really looking forward for your answer!

**Comment by madoar** [comment]
Yes, I've thought about this use-case in the recent past too.
Currently it is not possible to use the wizard as a static progress indicator.
The main reason for this is in my opinion the navigation approach the wizard is based on, where the wizard is progressed step by step.

I'm not against changing the wizard to also function as a static progress indicator.
Let's do some brainstorming, can you give me a short code example how you would like to use the wizard as a static progress indicator?

**Comment by sebiglesias** [comment]
Hello, sorry for not responding earlier. I made my custom "stepper" in this project: [here](https://github.com/sebiglesias/sig-ui) 

For what I can see, your wizard allows the user to fill a determined number of forms and after all those forms are finished, you submit their whole content.

What I propose, is for the user to be able to stop filling the forms, leave the page and probably fill them up later. So, maybe by passing a "step", as either an int or a different json structure, to tell your wizard to start at a determined step.

This is how I use my custom "progress-bar":

`<app-purchase-progress-bar [step]="getStepNumber(purchase)"></app-purchase-progress-bar>`

![image](https://user-images.githubusercontent.com/13668861/49244694-2ea37e00-f3ef-11e8-875f-92e2ce777f96.png)

**Comment by sebiglesias** [comment]
For the particular use case that I wanted to use your wizard, was for a contruction reseller process. The user, would fill forms depending on the stage/step of a purchase they made (specifically buying stone that came inside a container). Each step, requiring a specific form, but there could be days between filling one step and the next one.

**Comment by madoar** [comment]
So basically you just need the navbar, without the step content?
Only after clicking on a step indicator a window/popup opens where you can interact with the content of the step?

You don't need to wait until the wizard has been completed before you can submit information to a server.
You can do it whenever you want, for example at the end of a step using the `(stepExit)` output.

The problem you face when using `angular-wizard` is the initialization of the wizard at an arbitrary step, because you need to mark all previous steps as completed.
You can only do this currently by calling internal API methods.
In detail you would need to initialize the wizard at the first step and then transition through all done steps until you reach the currently entered step.

It is not possible to automatically set all previous steps to the step at which the wizard starts to done, because this is only possible if the `[canEnter]` and `[canExit]` inputs of all previous steps return true.
Because this can't be ensured, the wizard doesn't set previous steps to done automatically at startup.

**Comment by sebiglesias** [comment]
If you restrict the user coming back on previous, completed steps, maybe what you mentioned can be implemented:
```
to automatically set all previous steps to the step at which the wizard starts to done, because this is only possible if the [canEnter] and [canExit] inputs of all previous steps return true.
Because this can't be ensured, the wizard doesn't set previous steps to done automatically at startup.
```

**Comment by sagunpandey** [comment]
> If you restrict the user coming back on previous, completed steps, maybe what you mentioned can be implemented:
> 
> ```
> to automatically set all previous steps to the step at which the wizard starts to done, because this is only possible if the [canEnter] and [canExit] inputs of all previous steps return true.
> Because this can't be ensured, the wizard doesn't set previous steps to done automatically at startup.
> ```
> You could have an input attribute in your wizard that makes previous steps unreachable and so have a workaround for this "nav-bar-like" use case.

Hi, thank you for your inputs. So, is there a way to mark all the previous steps as done if I choose to set the initiate the wizard at some index?

**Comment by sebiglesias** [comment]
I ended up using a custom solution for my use case and not the wizard, because it didn't suit my particular case. 

Still, and I don't remember correctly or know of any recent changes, I couldn't find a way to initiate the wizard at some index with all previous steps finished, and I didn't (try to) understand the use I should give to `defaultIndexLocation`.

**Comment by madoar** [comment]
Through the combination of the `awCompletedStep` directive, which can be added to a `aw-wizard-step` and the `defaultStepIndex` input of the `aw-wizard` component, it becomes possible to implement a progress view.

To implement a progress view you need to add the `awCompletedStep` directive to every step in the wizard. Additionally you need to provide an input to the directive that checks whether the corresponding step has been completed (if you don't add such an input all steps will be shown as completed). To select the correct step after the wizard has been initialized you will also need to pass the correct index of the step to the `defaultStepIndex` input of the wizard.
