### ISSUE TITLE
Jump to specific step with an external link/button

### ISSUE THREAD

**Issue by samuray500** [madoar/angular-archwizard#171]
is there any way to jump to a specific step with a link that is outside of `<aw-wizard>` element?
I want to build my own navigation menu, and put it in a section located far away from the wizard.

We have this property to do it **`[awGoToStep]="{stepIndex: 1}"`**. But it only works inside of `<aw-wizard>` element.

**Comment by madoar** [comment]
You can let the wizard jump to a different step by using the internal API of the wizard.
For this you need to inject the wizard in your code via:
```typescript
@ViewChild('wizard')
public wizard: WizardComponent;
```

Afterwards you can navigate the wizard to another step by calling:
```typescript
wizard.navigation.goToStep(destinationStepIndex);
```

Please be aware, that this is an internal API call, which may be subject of change in the future.

**Comment by unsafecode** [comment]
@madoar Fine, but we definitely need public APIs to handle this, especially when dealing with dynamically created steps.

**Comment by madoar** [comment]
I agree, a public API becomes a requirement when working with dynamically created steps. 
The API should become more stable with #166

**Comment by madoar** [comment]
`angular-archwizard` version `5.0.0` has just been released. It contains #166 with a more stable API to navigate the wizard programmatically. Feel free to give it a try!

If there are any questions or problems feel free to open a new issue!
