### ISSUE TITLE
Angular4 issue.

### ISSUE THREAD

**Issue by ollita7** [madoar/angular-archwizard#175]
Im getting an error when i use angular4.
Is it posible that I mut install other verson?

ERROR in Error: Metadata version mismatch for module C:/Cavepot/Git/upwork-projects/fintitude/prototype/ui/node_modules/angular-archwizard/angular-archwizard.d.ts, found version 4, expected 3, resolving symbol AppModule

**Comment by madoar** [comment]
Yes, `angular-archwizard` version `3.0.0` works with Angular 5+.
For Angular 4 you'll need to install `ng2-archwizard` version `2.1.0`.

Please be aware, that release `2.1.0` is quite old.
This means, that not all features of version `3.0.0` are supported.
In addition the syntax has changed (mainly the prefix `aw` has been added in version `3.0.0`).
