### ISSUE TITLE
Wizard "onStepChange" event subscriber?

### ISSUE THREAD

**Issue by PauloRodrigues33** [madoar/angular-archwizard#176]
Is the AW has a "onStepChange" subscriber returning the new step index or step properties?

**Comment by rluvaton** [comment]
Unfortunately no, but I’m working on it

**Comment by rluvaton** [comment]
#178 pending Pull request for this issue

**Comment by madoar** [comment]
Currently the wizard doesn't provide such an output.
The current approach to observe step changes is by adding a function to the `stepEnter` or `stepExit` output of the steps in whose transitions you're interested (see also [here](https://github.com/madoar/angular-archwizard#stepenter)).

**Comment by madoar** [comment]
I'm not sure if this feature is really required as part of `angular-archwizard`. While a single (convenient) callback does not exist for this you could fetch the current step index using `WizardComponent#currentStepIndex` in combination with the `stepEnter` callback of the wizard steps. 

What do you think @earshinov?

**Comment by earshinov** [comment]
@madoar , I also think that the current functionality is enough.

**Comment by madoar** [comment]
Ok then I am closing this issue
