### ISSUE TITLE
Is it possible to modify the step to be also clickable on symbol

### ISSUE THREAD

**Issue by forvy** [madoar/angular-archwizard#180]
As in [demo](https://madoar.github.io/angular-archwizard-demo/#/navigation-symbol/basic) there are example as to how to use the angular-archwizard. But as you can notice we could only click on the title. Is there a way to make the symbol also clickable and behave the same way as the title?
![image](https://user-images.githubusercontent.com/17746819/50144438-d66ee600-02e1-11e9-8f43-2492bef1a3d5.png)
The best I could've done is expanding the `<a>` area by css. But it was arguable since height is interchangeable, by then you would need to update the css setting manually.

**Comment by earshinov** [comment]
Hello @forvy ,

This is already done in https://github.com/madoar/angular-archwizard/pull/147 and will be available in the next release of angular-archwizard (4.0.0).

**Comment by kenger** [comment]
There is an ETA for 4.0.0? #147 is now 4 month old but still not published.

Thanks for the awesome plugin!

**Comment by madoar** [comment]
I want to do a release soon. Before releasing version `4.0.0` I want to merge #186, which still requires some additional testing and a demo before I can merge it. Additionally I want to do some slight refactoring of tests before. 

The other remaining open PRs are likely to be merged for version `4.1.0` or `5.0.0`, depending on how large their impact is.
