### ISSUE TITLE
[navBarLayout]="large-filled" show Nan in HTML

### ISSUE THREAD

**Issue by shubh9415** [madoar/angular-archwizard#185]

**Comment by shubh9415** [comment]
<aw-wizard _ngcontent-c1="" ng-reflect-nav-bar-layout="NaN" class="horizontal">

**Comment by madoar** [comment]
Can you please provide a short code snippet producing this error.
In addition which version of `angular-archwizard` are you using?

**Comment by madoar** [comment]
Closed because of inactivity
