### ISSUE TITLE
Unspecified dependency to 'util' / Angular compilation error

### ISSUE THREAD

**Issue by mitschmidt** [madoar/angular-archwizard#188]
Great wizard - it does a superb job in our enterprise projects.

After running `npm audit fix`, my package-lock is being updated and gets rid of some global dependencies (i.e. `util` package).

Now on building my application with `angular-archwizard`, I am getting the following error:

```
ERROR in ../node_modules/angular-archwizard/esm5/angular-archwizard.js
Module not found: Error: Can't resolve 'util' in '/opt/atlassian/pipelines/agent/build/node_modules/angular-archwizard/esm5'
npm[app] ERR! code ELIFECYCLE
npm[app] ERR! errno 1
npm[app] ERR! ticketkalender@2.0.0 build-client-prod-analyze: `cd client && ng build --aot --prod --stats-json`
npm[app] ERR! Exit status 1
npm[app] ERR! 
npm[app] ERR! Failed at the ticketkalender@2.0.0 build-client-prod-analyze script.
npm[app] ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm[app] ERR! A complete log of this run can be found in:
npm[app] ERR!     /root/.npm/_logs/2019-02-15T18_11_04_252Z-debug.log
```

Has anybody seen this issue before? And shouldn't `util` be named as a dependency for angular-archwizard as this is only part of the `node` environment, but not of common browsers?

Thanks in advance

**Comment by madoar** [comment]
I haven't seen this error before. I'm not sure what the error means by `util`. `angular-archwizard` contains a folder with utility classes/functions, which is called `util`, maybe this one is meant?

**Comment by mitschmidt** [comment]
That is possible - in that case it might be a resolution issue? I was not able to build my project anymore - it seems it only worked before because some sub dependency relied on npm ´util´ package, which was removed after a recent dependency update in my project. I had to manually add `util` as a dev dependency to make it work again.
