### ISSUE TITLE
Creating dynamic component into wizard with many steps

### ISSUE THREAD

**Issue by Nascooo** [madoar/angular-archwizard#189]
hi all , 
refereeing to this issue [https://github.com/madoar/angular-archwizard-demo/issues/27#issue-413165950](url) 
is there a way to create components created dynamically and every component is show in it's step

**Comment by madoar** [comment]
What do you mean by `components created dynamically` and `every component is show in it's step`?

**Comment by madoar** [comment]
Closed because of inactivity
