### ISSUE TITLE
Navigate by Click on STEPTITLE Icon

### ISSUE THREAD

**Issue by EliezerMarkovsky** [madoar/angular-archwizard#190]
Hi
Thanks for the project, it looks great!
I want to use it on my site,
But I also need the option to perform navigation by clicking on the icons.
Do you have such a possibility, or can you easily create it?

![image](https://user-images.githubusercontent.com/46671900/53959740-2a24ea80-40ed-11e9-8fc8-4761cd8acca5.png)

**Comment by madoar** [comment]
This has been implemented in the current development version (version `4.0.0`). If everything goes well I will release it this weekend.

**Comment by madoar** [comment]
I've just released `angular-archwizard` version `4.0.0` to [npm](https://www.npmjs.com/package/angular-archwizard)! Feel free to give it a try!
