### ISSUE TITLE
ERROR TypeError: Cannot read property 'navigation' of undefined

### ISSUE THREAD

**Issue by suhailvs** [madoar/angular-archwizard#196]
When i run `ng serve` everything work perfectly. 

But when i take production build(`ng build --prod`) then when i click `Add To Cart` button, I got error(`ERROR TypeError: Cannot read property 'navigation' of undefined`) when i call `this.wizard.navigation.goToNextStep();`
here is the code:
        
    import { Component, OnInit, ViewChild } from '@angular/core';
    import { WizardComponent } from 'angular-archwizard';

	@Component({
	  selector: 'app-cart-addservice',
	  templateUrl: '../pages/addservice.component.html'
	})

	export class AddServiceToCartComponent implements OnInit 
          @ViewChild(WizardComponent)
          public wizard: WizardComponent;
          addTocart() {
              this.wizard.navigation.goToNextStep();
          }
          ngOnInit() {
          }
     }

**Comment by madoar** [comment]
Which version of `angular-archwizard` are you using?
When/where is `addTocart()` called?

**Comment by suhailvs** [comment]
@madoar 
Version

addtocart is a button, which will navigate to nextstep ie `this.wizard.navigation.goToNextStep();`.

Please put `@ViewChild('wizard') wizard: WizardComponent;` into documentation on how to change step on typescript. 

I found you have mentioned `@ViewChild(WizardComponent) public wizard: WizardComponent;` in some issues. That won't work on production build.

**Comment by madoar** [comment]
@suhailvs try version `4.0.0` which I released about a week ago, it should fix the issue :)
