### ISSUE TITLE
How to use *ngIf in wizard

### ISSUE THREAD

**Issue by candorthor** [madoar/angular-archwizard#201]
@madoar 

I need a help on solving the issue. I have a wizard, where I made step 3 and step 5 as optional step. When I click the "Next Step" button in step 1, I want step 2 and step 4 to be hidden and step 3 and step 5 to be displayed. I have used *ngIf. The problem is when clicked on "Next Step" button of step 1, wizard circle is working as expected, but the contents of the step 3 (i.e "Go to previous step" button and "Go to next step" button) are not displaying. Below is the code.

.html file
`<wizard> 
	<wizard-step stepTitle="Title of step 1" [canExit]='true'> 
		Content of Step 1 
		<button type="button" nextStep (click)="optional()">Next Step</button> 
	</wizard-step> 
	<wizard-step stepTitle="Title of step 2" *ngIf="optionStep === 'no'" ></wizard-step> 
	<wizard-step stepTitle="Title of step 3" *ngIf="optionStep === 'yes'" optionalStep> 
		Content of Step 2 
		<button type="button" previousStep>Go to previous step</button> 
		<button type="button" nextStep>Go to next step</button> 
	</wizard-step> 
	<wizard-step stepTitle="Title of step 4" *ngIf="optionStep === 'no'"></wizard-step> 
	<wizard-step stepTitle="Title of step 5" *ngIf="optionStep === 'yes'" optionalStep> 
		Content of Step 3 
		<button type="button" previousStep>Previous Step</button> 
		<button type="button">Finish</button> 
	</wizard-step> 
</wizard>
`

.ts file
`import { Component } from '@angular/core';

@component({
selector: 'my-app',
templateUrl: './app.component.html',
styleUrls: [ './app.component.css' ]
})
export class AppComponent {
optionStep: any;
name = 'Angular 5';

constructor() {
this.optionStep = 'no'
}

optional() {
this.optionStep = 'yes'

}
}`

**Comment by madoar** [comment]
Your code is hard to read because of the missing formatting (especially the html). Can you please format your code and put it inside code tags, this makes it much easier to read. 

I'm not sure what exactly you want to do. Can you provide a screenshot visualizing what you want to do? 

Please be aware that removing and reinserting wizard steps at runtime (e.g. with `*ngIf`) can have quite the unexpected results. One possible issue with this is, that the wizard can jump to a different step internally when a step is removed or added to the wizard. Another possible issue is that a wizard could forbid further navigation if a wizard step is added after initialisation.

**Comment by candorthor** [comment]
@madoar 

Sorry, the code formatting was my mistake. Below are the codes. Initially it will be on the step 1. Here I want step 2 and step 3 to be enabled when clicked on the "Next step" button of step 1 and the "Go to previous step" button" and "Go to next step" button of step 2 should be displayed as shown in the attachment . I have attached the screenshot for your reference.
.html file

```
<wizard>
	<wizard-step stepTitle="Title of step 1" [canExit]='true'>
		Content of Step 1 
		<button type="button" nextStep (click)="optional()">Next Step</button>
	</wizard-step> 
	<wizard-step stepTitle="Title of step 2" *ngIf="optionStep === 'no'" ></wizard-step>
	<wizard-step stepTitle="Title of step 2" *ngIf="optionStep === 'yes'" optionalStep> 
		Content of Step 2 
		<button type="button" previousStep>Go to previous step</button>
		<button type="button" nextStep>Go to next step</button>
	</wizard-step> 
	<wizard-step stepTitle="Title of step 3" *ngIf="optionStep === 'no'"></wizard-step> 
	<wizard-step stepTitle="Title of step 3" *ngIf="optionStep === 'yes'" optionalStep> 
		Content of Step 3 
		<button type="button" previousStep>Previous Step</button> <button type="button">Finish</button> 
	</wizard-step> 
</wizard>
```

.ts file
```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  name = 'Angular 5';
  optionStep: any;

constructor() {
this.optionStep = 'no'
}

optional() {
this.optionStep = 'yes'

}
}
```
Below are the screenshots.
Initially it should look like this.
![Initial](https://user-images.githubusercontent.com/49184671/55604726-ea562f00-578e-11e9-9839-d939257e7fa8.PNG)

After clicking on the "Next Step" of the step 1, it should display like below. where step3 and step 3 are enabled.
![After](https://user-images.githubusercontent.com/49184671/55605093-86cd0100-5790-11e9-853d-0596fac2aac0.PNG)

**Comment by candorthor** [comment]
@madoar
Any updates?

**Comment by madoar** [comment]
What do you mean by "enabled"? In your second screenshot all steps are completed, this can be achieved by added a completion step to your wizard and entering it.

What you seem to want to do in your example is exchanging whole steps when flipping a variable. I can't recommend this. because of the previously mentioned issues. Instead I recommend changing the content of the steps and not the steps themselves:

```html
<wizard-step stepTitle="Title of step 2"></wizard-step>
   <div *ngIf="optionStep === 'no'">
      ...
   </div>
   <div *ngIf="optionStep === 'yes'">
      ...
   </div>
</wizard-step> 
```

**Comment by candorthor** [comment]
@madoar
Thanks for the suggestion.

Enabled in the sense the steps are completed. What  I wanted  is to complete step 2 and step 3 on a click on "Next step" button of step 1, like I have shown in the screenshot. So is that possible?

**Comment by candorthor** [comment]
@madoar 

I fixed this. Thank you :)

**Comment by ramyalathaseethala** [comment]
> optionStep

@candorthor Can I know how did you fixed this issue?
