### ISSUE TITLE
Change the navigation symbol on complete

### ISSUE THREAD

**Issue by apbedi** [madoar/angular-archwizard#202]
How can I change the navigation symbol on complete the step. I was also not able the change the css for stepper

**Comment by madoar** [comment]
You can find an example how to do this in the [demo](https://github.com/madoar/angular-archwizard-demo) repository. To be more precise https://madoar.github.io/angular-archwizard-demo/#/navigation-symbol/basic shows a wizard with custom navigation symbols for the steps. https://github.com/madoar/angular-archwizard-demo/blob/develop/src/app/basic-step-symbol/basic-step-symbol.component.html contains the related code.
