### ISSUE TITLE
Completing a particular wizard step on a click

### ISSUE THREAD

**Issue by candorthor** [madoar/angular-archwizard#207]
@madoar 

This is the perfect wizard for what I'm trying to do. Here Iam facing a problem. Could you please help me on this.

I have a wizard like I have shown in the screenshot. When I click on the  button "Enter Details in 4"  in step 4, it is routed to a page, say a "details" page (somewhere outside the wizard). 
In "details" page I have a button "Save". 

What I want to do is, when I click on the "Save" button, the wizard step 4 should be completed (color of the wizard circle should be green i.e completed state). Unless and until I click on "Save" button on "details" page, step 4 shouldn't be complete. How can I do this?

![Details step 4](https://user-images.githubusercontent.com/49184671/56561233-54ab0400-65c4-11e9-8dc0-8bfa0b4f4d92.PNG)

wizard.html

```
<wizard [navigationMode]="'semi-strict'" [defaultStepIndex]="1">
  <wizard-step stepTitle="Title of step 1"  optionalStep>
    Content of Step 1
    <button type="button" nextStep>Next Step</button>
  </wizard-step>
  <wizard-step stepTitle="Title of step 2">
    Content of Step 2
    <button type="button" >Enter Details in step 2</button>
    <button type="button" nextStep>Go to next step</button>
  </wizard-step>
  <wizard-step stepTitle="Title of step 3">
    Content of Step 3
    <button type="button">Enter Details in 3</button>
    <button type="button" nextStep>Go to next step</button>
  </wizard-step>
  <wizard-step stepTitle="Title of step 4">
    Content of Step 4
    <button type="button" [routerLink]="['/details']" [queryParams]="{enterDetails: 'enterDetails'}">Enter Details in 4</button>
    <button type="button" nextStep>Go to next step</button>
  </wizard-step>
  <wizard-step stepTitle="Title of step 5">
    Content of Step 5
    <button type="button" >Enter Details in 5</button>
    <button type="button" nextStep>Go to next step</button>
  </wizard-step>
  <wizard-step stepTitle="Title of step 6">
    Content of Step 6
    <button type="button">Enter Details in 6</button>
    <button type="button" >Finish</button>
  </wizard-step>
</wizard>
```

wizard.ts
```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  constructor() {
    
    }
}
```

details.html
`<button type="button"  (click)="saveDetails()">Save</button>`

**Comment by madoar** [comment]
`angular-archwizard` doesn't support this out of the box, but there is a workaround you could use.

Basically you need to change the style of the step indicator in the navigation bar of your fourth step upon pressing the `Enter` button to display the step as completed. The easiest way to do this in my opinion is by giving the wizard step a `stepId`, which you change depending on whether the user has clicked on the `Enter` button.

For an example please take a look [here](https://madoar.github.io/angular-archwizard-demo/#/custom-css/step) and [here](https://github.com/madoar/angular-archwizard-demo/tree/master/src/app/custom-step-css)

**Comment by candorthor** [comment]
That's great. Thanks for your suggestion :)
