### ISSUE TITLE
Font Awesome again

### ISSUE THREAD

**Issue by tbenci** [madoar/angular-archwizard#212]
Howdy all,

I have a brand new project with 

"@fortawesome/fontawesome-free": "^5.8.2",

I can not get these icons to work.

[navigationSymbol]="{ symbol: '&#xf2dd;', fontFamily: 'Font Awesome 5 Free' }"

All I get is the square box everyone was talking about on the closed thread.

I am using
"angular-archwizard": "^4.0.0",

Any help appreciated or do I just stop flogging the dead horse.

Thanks
Tony

**Comment by madoar** [comment]
Can you try if using a `ng-template` with `awWizardStepSymbol` works?
You can find an example for this [here](https://madoar.github.io/angular-archwizard-demo/#/navigation-symbol/custom-template) and [here](https://github.com/madoar/angular-archwizard-demo/blob/master/src/app/custom-step-symbol-template/custom-step-symbol-template.component.html).

As far as I remember starting with version 5 font-awesome required some additional styling properties which aren't set when using `[navigationSymbol]="{ symbol: '', fontFamily: 'Font Awesome 5 Free' }"`. This can be solved by using `awWizardStepSymbol`.

**Comment by chispaK** [comment]
Good day tbenci:
Did you manage to get this resolved? Ran into this issue today but unable to get fortawesome icon rendered see sample step code below:

```
<aw-wizard-completion-step [stepTitle]="'Setup Complete'">
      <ng-template awWizardStepSymbol><i class="fas fa-handshake-alt"></i></ng-template>
      <app-registration-complete  
      ></app-registration-complete>
      <div></div>
    </aw-wizard-completion-step>
```

The icon does not get rendered. Can you tell what I am doing incorrect?

**Comment by madoar** [comment]
Does the above linked example work for you? Have you tried displaying an fontawesome icon outside of `angular-archwizard` in your application? Have you checked that fontawesome is correctly setup in your project, i.e. both installed and added to your stylesheets?

**Comment by chispaK** [comment]
Hi madoar:

Sorry for the trouble. I just realized I did not update my package to the latest. all now works as expected.
