### ISSUE TITLE
Step indicator of completion steps has wrong color after entering

### ISSUE THREAD

**Issue by madoar** [madoar/angular-archwizard#213]
After entering a completion step the corresponding step-indicator in the navigation bar is red instead of dark green:

![grafik](https://user-images.githubusercontent.com/18488086/57882391-dc7ed980-7823-11e9-8043-854943843757.png)

Correct would be if the step indicator is dark green like for the other steps.

**Comment by madoar** [comment]
The reason for the issue is that the completion step is assigned the css classes `current done completed` after entering.

This combination is then displayed with:

https://github.com/madoar/angular-archwizard/blob/57900c5ec9c354b259669696bf436db000c0c1df/src/css/wizard-navigation-bar.scss#L163-L168

**Comment by madoar** [comment]
A possible quick fix for the issue may be to add an additional constraint to the `current` css class check. This would change:

https://github.com/madoar/angular-archwizard/blob/57900c5ec9c354b259669696bf436db000c0c1df/src/lib/components/wizard-navigation-bar.component.ts#L69-L71

to:

```typescript
public isCurrent(wizardStep: WizardStep): boolean {
    return wizardStep.selected && !this.wizard.completed;
}
```

**Comment by madoar** [comment]
At the moment I do not think that the suggested quick-fix is a good solution, because it reduces the possible expressiveness of the CSS by allowing the removal of the `selected` css class from the navigation bar, while a wizard step is in fact selected.

Another more sophisticated solution may be to use `:not(.completed)` to specify the condition when to apply certain css in a more detailed way.

**Comment by earshinov** [comment]
As far as I understand, the problems stems from the fact that completion steps are marked as completed right after they are navigated to by the user. I think the best course of action would be to adjust the condition when the red `$wz-color-editing` color is applied. Right now it is applied to any steps which happen to be selected and completed at the same time (which is, of course, true for the completion step in the described scenario). Instead, this red color should be applied to the selected step if it was already completed *before* the user navigated to it. We are going to need an additional `.editing` CSS class, and perhaps an additional field in the `WizardStep` class as well. In the result, we will have the following CSS classes for steps:

```
.optional - for any optional steps

.navigable - for any steps which user could go to using the navigation bar

.done - for any completed steps

.current - for the selected step

.editing - for the selected step, if the user has already completed it before

.completed - added to all steps when the whole wizard is completed
```

The `.current` and `.editing` classes are not mutually exclusive (namely, `.editing` can only appear on a `.selected` step), but it seems fine to me. @madoar , what do you think?

**Comment by madoar** [comment]
I'm fine with that solution! This will also be more in line with the previous versions of `angular-archwizard` which also contained an `.editing` css-class with the same meaning.
