### ISSUE TITLE
Why the sample is displaying the contents of all steps?

### ISSUE THREAD

**Issue by hamdyahmed1984** [madoar/angular-archwizard#215]
Why the sample is displaying the contents of all steps?

![image](https://user-images.githubusercontent.com/6085098/58779977-c6209e00-85d7-11e9-80ea-e1151cf73dc7.png)

**Comment by madoar** [comment]
To better help with your problem I need context information:
- what wizard are you using? (is it from the demo repository or your own code?)
- what code produces this result?
- what version of `angular-archwizard` are you using?
- what browser are you using? (have you tested with other browsers?)

The more information you can provide the easier it is to help

**Comment by hamdyahmed1984** [comment]
Nothing special, just used angular 8.
- Installed archwizard using npm: 
$ npm install --save angular-archwizard
- Added it in the AppModule.
- And used the sample code:
<aw-wizard>
  <aw-wizard-step stepTitle="Title of step 1">
    Content of Step 1
    <button type="button" awNextStep>Next Step</button>
    <button type="button" [awGoToStep]="{stepIndex: 2}">Go directly to third Step</button>
  </aw-wizard-step>
  <aw-wizard-step stepTitle="Title of step 2" awOptionalStep>
    Content of Step 2
    <button type="button" awPreviousStep>Go to previous step</button>
    <button type="button" awNextStep>Go to next step</button>
  </aw-wizard-step>
  <aw-wizard-step stepTitle="Title of step 3">
    Content of Step 3
    <button type="button" awPreviousStep>Previous Step</button>
    <button type="button" (click)="finishFunction()">Finish</button>
  </aw-wizard-step>
</aw-wizard>

**Comment by madoar** [comment]
Do you have a short example project producing this issue?
To analyze this I need to look at the generated HTML and DOM.

**Comment by hamdyahmed1984** [comment]
I tried it in a new angular 8 app and it works fine.
Seems that my app has some dependency or config that causes this issue.

**Comment by juwul** [comment]
I had similar issues. My problem was that I used _lookbehind_ regex for form validation patterns. But _lookbehind_ is only supported by Chrome. So after changing it to a new regex that did not use _lookbehind_ everything works like a charm.
