### ISSUE TITLE
Angular pure style library (or node pkg) which can used in different angular applications as a global style.

### ISSUE THREAD

**Issue by vishal4799** [madoar/angular-archwizard#216]
For example, I have three ongoing projects in which I have the same global _variable.scss and global.scss. When I change anything in these, I have to copy it to all three projects Instead I can create library/npm pkg which can be used in any number of project.

**Comment by madoar** [comment]
What exactly do you mean by `pure style library`?

**Comment by vishal4799** [comment]
Only CSS no HTML and TS.

**Comment by madoar** [comment]
How would such a library be of use? I mean the styles make only sense if you have a corresponding html layout?

I have just released version `5.0.0` of the wizard. This version comes with a separate css file, that contains **all** the stylesheets defined in the wizard. See the documentation for more details.

**Comment by madoar** [comment]
I take it that this issue has been solved by the new css file released with version `5.0.0`. If you are still facing this problem feel free to open a new issue.
