### ISSUE TITLE
Change the step icon's style/innerHtml

### ISSUE THREAD

**Issue by Gevko** [madoar/angular-archwizard#222]
Hello,

Some months ago I had a problem and it was solved here: https://github.com/madoar/angular-archwizard/pull/186 , by adding a stepId for each wizard's step. I needed to add an error symbol to the wizard's step if the step had any errors, and I was doing it this way:

const stepElmnt = document.getElementById('stepsId');
stepElmnt.innerHtml += 'someHtmlThatWillPutAnErrorIconToStep';

Now i tried again to do the same thing, but I can not get the element by id, since with the latest wizard's version the value of stepElmnt is always undefined. What should I do to reproduce the same thing I did earlier?

Thanks, Gevko.

**Comment by madoar** [comment]
So basically you want to add a symbol to a step-indicator in the navigation bar? If you can't get the correct element by its id I think you're either trying to access the element before it has been created (wrong angular lifecycle phase) or somehow the element does not exist.

Can you share the created DOM tree for your code or a code-sample that produces the error? (a screenshot from a browser debugger should be ok).

**Comment by Gevko** [comment]
Hello,

The first print is the wizard instance's log, and the second is the DOM.

As you can see, my first step's stepId is "brigade", and i log it with console.log(document.getElementById('brigade')); and the log is null. Also this can not be angular lifecycle problem, since I log this on a button click long after the wizard is created. But this was working this way at the version you provided me some month ago.


![Capturar1](https://user-images.githubusercontent.com/26480544/60086792-a80c1080-9733-11e9-9866-aa2b73a5b79d.PNG)
![Capturar2](https://user-images.githubusercontent.com/26480544/60086793-a80c1080-9733-11e9-9bc1-4165a57165d0.PNG)

**Comment by madoar** [comment]
Which version of `angular-archwizard` are you using?

**Comment by Gevko** [comment]
4.0.0

**Comment by madoar** [comment]
This is strange. Can you provide a minimal example leading to this issue?

We have an example for the `stepId` feature at https://madoar.github.io/angular-archwizard-demo/#/custom-css/step and https://github.com/madoar/angular-archwizard-demo/blob/master/src/app/custom-step-css/custom-step-css.component.html#L13. Does your code differ from this?

**Comment by Gevko** [comment]
Nope, my code is similar to yours.

<aw-wizard #wizard [navBarLayout]="'large-filled-symbols'" class="custom-css">
<aw-wizard-step stepId="brigade" [stepTitle]="'components.fieldNames.general' | translate" [navigationSymbol]="{symbol: '1'}">
Some content...
</aw-wizard-step>
<aw-wizard>

at .ts file i have a test method:
	test() {
		console.log(document.getElementById('brigade'));
	}

This always logs me null.

**Comment by madoar** [comment]
I need a minimal code example that leads to the error, otherwise it is hard for me to help.

**Comment by Gevko** [comment]
`<aw-wizard #wizard [navBarLayout]="'large-filled-symbols'" class="custom-css">
		<aw-wizard-step [stepId]="'brigade'" [stepTitle]="'labels.generalFields' | translate" [navigationSymbol]="{symbol: '1'}">
			HELLO THIS SHOULD BE WORKING x)
		</aw-wizard-step>
</aw-wizard>
`

and i have a method on ts file:
`	test() {
		console.log(document.getElementById('brigade'));
	}`

this logs me null, is this code enough? :)

**Comment by madoar** [comment]
No this is only a snippet which misses a lot of information. Please provide a runnable example web-application that demonstrates your error. You can this either in a new Github repository or through a website like stackblitz. Without such an example it is really hard for me to reproduce the issue and thereby to help fix it.

**Comment by Gevko** [comment]
So here it is:
https://stackblitz.com/edit/angular-pgrkea
the aler always logs null...

**Comment by madoar** [comment]
After updating the version of `angular-archwizard` from `3.0.0` to `4.0.0` it was working for me.
I would recommend you updating all the way to `5.0.0`.

**Comment by Gevko** [comment]
gonna try out :)

**Comment by madoar** [comment]
I take it as the problem has been solved? If you still face this issue feel free to open a new issue
