### ISSUE TITLE
How to retrieve data from Form in dynamically wizard in angular 6

### ISSUE THREAD

**Issue by vahidsamimi** [madoar/angular-archwizard#231]
I'm trying to create dynamically form-wizard with angular-archwizard and I want to retrieve data from Form for each step as JSON when a user clicks on the finish button. Hier is my code as an example :

https://stackblitz.com/edit/angular-5-step-wizard-pzxmco

**Comment by madoar** [comment]
To do this you will need to store the input of your form fields in a central data structure, i.e. json object. Afterwards you can access this json object in `click` event handler of your finish button.
