### ISSUE TITLE
ERROR TypeError: Cannot read property 'changes' of undefined, Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by karivka** [madoar/angular-archwizard#232]
Hi, 

Recently in my project, I've updated  angular-archwizard  from 4.0.0 to 5.0.0

When I run ng serve everything works perfectly, but when I make production build(ng build --prod) I get a lot of errors:

ERROR TypeError: Cannot read property 'changes' of undefined
    at l.ngAfterContentInit 
(it cannot find this.wizardSteps )
ERROR TypeError: Cannot read property 'length' of undefined
    at l.get [as numberOfWizardSteps] 

In my usage, I don't have type references 
@ViewChild(WizardComponent) public wizard: WizardComponent;
 and I use it only in the template.

Any suggestions, what can be wrong?

**Comment by madoar** [comment]
Can you share some more of your code? I can't really tell what is happening by looking at your error message. For example what is `l`?

**Comment by karivka** [comment]
I use the wizard in many places, so I created just a simple example to test prod build version:

<aw-wizard [navBarLocation]="'left'" [navBarLayout]="'large-empty-symbols'" class="custom-css">
    <aw-wizard-step stepTitle="Base Information"
                    [navigationSymbol]="{ symbol: '&#xf085;', fontFamily: 'FontAwesome' }"
                    [canExit]="true"
                    stepId="customStep">
        Base step
        <div class="action-panel">
            <button type="button" class="btn mr-2" awNextStep>Next</button>
        </div>
    </aw-wizard-step>
    <aw-wizard-step *ngFor="let testStep of [1, 2, 3, 4, 5]" [stepTitle]="testStep"
                    [navigationSymbol]="{symbol: '&#xf1e0;', fontFamily: 'FontAwesome' }"
                    [canExit]="true" >
        {{testStep}} step
        <div class="action-panel">
            <button type="button" class="btn mr-2" awNextStep>Next</button>
            <button type="button" class="btn mr-2" awPreviousStep>Previous</button>
        </div>
    </aw-wizard-step>
</aw-wizard>

The same errors in prod js files

![image](https://user-images.githubusercontent.com/42419088/63611322-9f0bb400-c5a9-11e9-8c86-31421a005330.png)

**Comment by madoar** [comment]
Have you tried the corresponding [example](https://github.com/madoar/angular-archwizard-demo/tree/develop/src/app/wizard-step-ngfor)?

Inside the associated [typescript file](https://github.com/madoar/angular-archwizard-demo/blob/develop/src/app/wizard-step-ngfor/wizard-step-ngfor.component.ts) is an additional:

```typescript
  ngAfterViewInit(): void {
    // Force another change detection in order to fix the ngFor error
    this._changeDetectionRef.detectChanges();
  }
```

definition. I can't remember anymore why it way needed but maybe it helps in your use-case?

**Comment by karivka** [comment]
this._changeDetectionRef.detectChanges(); 
this is needed when you change <aw-wizard-step> steps in template after first initialization , in my case I didn't change anything after initialization.

Can be these issue related to angular version(I have old version 6.0.0)?

**Comment by madoar** [comment]
Yes that is quite possible. `angular-archwizard` version `5.0.0` is built using Angular 8. So it may be incompatible with Angular 6.

**Comment by earshinov** [comment]
@madoar, Judging by the code it seems that `@ContentChildren(WizardStep) wizardStepsQueryList` for some reason is not yet initialized in `ngAfterContentInit`. Here is where the first "Cannot read property 'changed' of undefined" errors comes from: https://github.com/madoar/angular-archwizard/blob/6aad9dc691a09e3947309173f6b167ae0cc99bde/src/lib/components/wizard.component.ts#L167

**Comment by madoar** [comment]
Yes, you're right the error comes most likely from `ngAfterContentInit`. The issue is that this should not happen. Therefore I think that the most likely reason is either the used Angular version or some strange usage of `angular-archwizard` in the target application.

**Comment by karivka** [comment]
I don't know what was the issue with updating from 4.0.0 to 5.0.0, with angular 6.
I tried different approaches with code and build setting, the issue probably related to some inconsistency with modules and versions, so I totally removed "node_modules" folder and install all dependencies again - that helped.
