### ISSUE TITLE
Consider removing !global

### ISSUE THREAD

**Issue by darrynhoskingluna** [madoar/angular-archwizard#239]
When including this library in an Angular 8 project and importing the SCSS files so i can override the variables, you get warnings.

When including like this to override the size of the dot

$wz-big-dot-width: 25px !default;
$wz-big-dot-height: 25px !default;
@import "~angular-archwizard/archwizard.scss";

This warning is printed when building

> DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
> declare new variables. Since this assignment is at the root of the stylesheet,
> the !global flag is unnecessary and can safely be removed.
> 
>    ╷
> 44 │ $wz-param-indicator-state: null !global;
>    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    ╵
>     node_modules\angular-archwizard\variables.scss 44:1  @import
>     node_modules\angular-archwizard\archwizard.scss 1:9  @import
>     stdin 14:9                                           root stylesheet
> 
> DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to
> declare new variables. Since this assignment is at the root of the stylesheet,
> the !global flag is unnecessary and can safely be removed.
> 
>    ╷
> 47 │ $wz-param-indicator-color: null !global;
>    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    ╵
>     node_modules\angular-archwizard\variables.scss 47:1  @import
>     node_modules\angular-archwizard\archwizard.scss 1:9  @import
>     stdin 14:9                                           root stylesheet

**Comment by madoar** [comment]
Thanks for reporting!

@earshinov you are more knowledgeable about SCSS than me, can you please share your thoughts on this?

**Comment by darrynhoskingluna** [comment]
@madoar no problem, to remove the warning it is fairly simple, just doing as the warning suggests and removing the !global from the two reported lines. 

In variable.scss 
change line 44 
` $wz-param-indicator-state: null !global;`
to 
`$wz-param-indicator-state: null;`
Change line 47 
`$wz-param-indicator-color: null !global;`
to 
`$wz-param-indicator-color: null;`

These changes are enough to fix the warning, but i see there is a few other uses of !global i am also not 100% sure if these should be removed at all.

**Comment by earshinov** [comment]
Hi @madoar , @darrynhoskingluna .

`!global` at root level serves no purpose indeed. I will prepare a PR to remove them.

Other usages are needed. Otherwise, each of them will declare a new variable instead of re-defining a global one.
