### ISSUE TITLE
Angular ng build command with --aot=true gives an error

### ISSUE THREAD

**Issue by uifortdev** [madoar/angular-archwizard#243]
Hello,

I'm using Angular 8.

When running ng build with --aot set to true, i'm getting this error:

`ERROR in node_modules/ng2-archwizard/dist/components/wizard-navigation-bar.component.d.ts.WizardNavigationBarComponent.html(17,11): Directive GoToStepDirective, Expected 0 arguments, but got 1.`

and in my view file:
```
Directive NextStepDirective, Expected 0 arguments, but got 1.
Directive GoToStepDirective, Expected 0 arguments, but got 1.
Property 'finishFunction' does not exist on type 'TestComponent'.
```

**Comment by dcherniy** [comment]
Looks like that package on NPM isn't being updated anymore, make sure you're installing via
`npm install --save angular-archwizard`
and not
`npm install --save ng2-archwizard`

Some of the components and directives are named different too so make sure you don't forgot to rename them!

**Comment by uifortdev** [comment]
Thanks for your answer! I confused the NPM packages :)

**Comment by madoar** [comment]
@dcherniy thank you for answering!

Here some more context about the name change:
Either between the transition from Angular 3 to 4 or 4 to 5 I renamed the library from `ng2-archwizard` to `angular-archwizard` because the old name was not fitting anymore. See also #52 for more information.

**Comment by sfrinx** [comment]
Hello, 
I delevop an app with Ionic 5 (Angular 8). When i try to build with production enviroment i see this error:

`ERROR in Directive WizardCompletionStep in /Users/scaminati/Documents/workspaces/github/Fait/easyfait/node_modules/angular-archwizard/angular-archwizard.d.ts has no selector, please add it!
[ng] Directive WizardStep in /Users/scaminati/Documents/workspaces/github/Fait/easyfait/node_modules/angular-archwizard/angular-archwizard.d.ts has no selector, please add it!
[ng] Cannot determine the module for class WizardCompletionStep in /Users/scaminati/Documents/workspaces/github/Fait/easyfait/node_modules/angular-archwizard/angular-archwizard.d.ts! Add WizardCompletionStep to the NgModule to fix it.
[ng] Cannot determine the module for class WizardStep in /Users/scaminati/Documents/workspaces/github/Fait/easyfait/node_modules/angular-archwizard/angular-archwizard.d.ts! Add WizardStep to the NgModule to fix it.`

I fix the problem by remove "aot": true and "buildOptimizer": true, on angular build chain. But i don't want to remove this.

Could you add support for aot?

Thanks a lot!
