### ISSUE TITLE
Request: Optional Directive optional

### ISSUE THREAD

**Issue by ronniehicks** [madoar/angular-archwizard#246]
Looking to use the awOptionalStep directive optionally. See code snippet for example

```JavaScript
<aw-wizard>
  <aw-wizard-step [stepTitle]="wizard.header" [awOptionalStep]="wizard.optional" *ngFor="let wizard of wizardSteps; let first = first; let last = last;">
    …
  </aw-wizard-step>
</aw-wizard>
```

**Comment by madoar** [comment]
We currently do not support this, but in hindsight that we support this for the `awCompletedStep` directive I think this would be a nice addition. The necessary changes shouldn't be too hard. So if you want to give this a try you are welcome!

Basically you only need to add a new input variable to [`awOptionalStep`](https://github.com/madoar/angular-archwizard/blob/ce015340584492e15e38383a2f3b1cbe0d7981fb/src/lib/directives/optional-step.directive.ts). This input variable then needs to be used in the `ngOnInit` method. As a reference you can look at the implementation of [`awCompletedStep`](https://github.com/madoar/angular-archwizard/blob/ce015340584492e15e38383a2f3b1cbe0d7981fb/src/lib/directives/completed-step.directive.ts).
