### ISSUE TITLE
How to validate a form inside a custom component

### ISSUE THREAD

**Issue by hssamconf** [madoar/angular-archwizard#247]
I have a wizard that contains a custom component as step and this component contains a form
I want to validate the form before exiting the step with canExit

```html
<aw-wizard>
  <app-custom-step
    (submitEvent)="catchSubmitEvent($event)"
    [canExit]="canExitCustomStep"
    awWizardStep></app-transaction>
...
</aw-wizard>
```
```typescript
catchSubmitEvent($event: boolean) {
    this.canExitCustomStep = $event;
}
```

my custom step :

```html
<form (ngSubmit)="onSubmit(formdata.value)" [formGroup]="formdata">
  <input  formControlName="emailid" required="true" type="email">
  <button awNextStep type="submit">Next</button>
</form>
```
```typescript
onSubmit(value: any) {
  this.submitEvent.emit(this.formdata.valid)
}
```
When i use this approch of emmiting the form validation result to my wizard CanExit runs before catching submitEvent
I think this is not the right approach

**Comment by madoar** [comment]
I have two approaches that would work:

1) The first approach splits the logic in two parts:
    - a **validation** part and
    - a **navigation** part

    Both parts are represented by their own button. First the user needs to click on the `validate` button. After the validation succeeded a property `canExistCustomStep` is set to `true`. This in turn enables the `navigation` button (e.g. the `next` button), which can then be used to navigation to the next step.
2) The second approach uses the navigation methods of the `WizardComponent`. Instead of clicking setting `canExitCustomStep` to `true` you would call `wizard.goToNextStep()`. For more details about this approach see also [here](https://github.com/madoar/angular-archwizard#navigating-the-wizard-programmatically)

**Comment by hssamconf** [comment]
Thank @madoar for your answer i think the second approach is what i am looking for:
I solved it with : 
```html
<aw-wizard #wizzard>
    <app-custom-step awWizardStep stepTitle="custom"
                (submitSucceded)="wizzard.goToNextStep()">
    </app-custom-step>
    ...
</aw-wizard>
```
and on my custom step :

```html
<form (ngSubmit)="onSubmit()" [formGroup]="formdata">
  <input  formControlName="emailid" required="true" type="email">
  <button type="submit">Next</button>
</form>
```
```typescript
@Output()
submitSucceded = new EventEmitter()

onSubmit() {
    if (this.formdata.valid) {
      this.submitSucceded.emit()
    }
}
```
