### ISSUE TITLE
Arch Wizard Step Indicator Not responsive for mobile View.

### ISSUE THREAD

**Issue by gauravmasand09** [madoar/angular-archwizard#248]
Hi ,
Angular-archwizard - 5.0.0
Angular Version - 8.0.0

I have been trying to make the angular-archwizard responsive for mobile view for Steps Indicators.
When the steps indicators are more than 3 its breaking the view on my mobile.
![rsz_screenshot_from_2019-11-01_20-41-48](https://user-images.githubusercontent.com/24978368/68034797-65150780-fce8-11e9-9363-b977e057c2cb.png)

When the step titles are being increased at that time what should i do to make it responsive.

**Comment by madoar** [comment]
As of now `angular-archwizard` is not optimized for mobile devices, like you have discovered.
The main problem is that none of the styles are fully functional on small devices especially if you have a larger number of steps.

A possible solution would be to use the vertical layout and tweak it a little. 
With "tweak it a little" I mean to do the following changes:
- remove the `position:sticky` attribute from the navigation bar
- remove the `flex` properties from the wizard parent panel, e.g. `flex-direction:row`, `display:flex` and `justify-content:flex-start`
- remove `min-width:280px` from the navigation bar
- change `width:20%` to `width:100%` for the navigation bar

This is how the demo application would look like after the changes:
![small-screen](https://user-images.githubusercontent.com/18488086/68054921-c12f5a00-fcef-11e9-9fca-c4fb80ea4a14.png)

The problem with this solution is that it is a hacky solution.
To create a clean solution we first need to decide if and if so how we want to support mobile devices/screens. Currently I would say that it makes sense to support such devices, but I have no idea how to solve the following issues/questions:
- how should a wizard look on a mobile device where not all steps fit on the screen?
- who is responsible for detecting whether the wizard is shown on a mobile device (i.e. a small screen) or on a "normal" device (i.e. a normal screen)? Angular? The user of `angular-archwizard`? `angular-archwizard` itself?

@earshinov do you have an opinion about this?

**Comment by earshinov** [comment]
My basic opinion is that angular-archwizard itself cannot know how the library user would like to structure the page. Even if angular-archwizard comes up with _some_ solution, chances are that this solution will suit _some_ users, but not others.

Out of curiosity I just had a look at a similar component from Angular Material UI kit, [Stepper](https://material.angular.io/components/stepper/overview). There they have distinct horizontal and vertical "steppers", just like angular-archwizard has horizontal and vertical layout. And the horizontal stepper's presentation happens to suffer on low-res screens, too (https://jbarbqnornx.angular.stackblitz.io/):

![image](https://user-images.githubusercontent.com/52021/68075391-39615280-fdb8-11e9-83d5-cdc45e791a24.png)

I would leave solving this problem to the library user (probably with help of custom styles as you demonstrated).

**Comment by gauravmasand09** [comment]
Hi @madoar 
Responsiveness is a big issue considering form wizards.I have gone through a  lot of libraries but all seems to struggle when to comes to mobile view even Angular Mat Stepper is not responsive as @earshinov  mentioned.

My Suggestions
#1 Can we do something like this when the user switches to lower resolution screens we can change change the horizontal archwizard to opt for vertical one so that it will be responsive. Changing the horizontal to vertical archwizard on screen resoltion changes. For lower screen it will change to vertical archwizard we can do something like this.

#2 My second suggestion is making it scrollable as the screen size reduces we will be showing only one arch-step at a time i mean as we shoiwng it for forms one at a time.We can show one step title at a time when screen size reduces.

Thanks 
(Give your views on my suggestions)

**Comment by madoar** [comment]
> #1 Can we do something like this when the user switches to lower resolution screens we can change change the horizontal archwizard to opt for vertical one so that it will be responsive. Changing the horizontal to vertical archwizard on screen resoltion changes. For lower screen it will change to vertical archwizard we can do something like this.

This should be possible, but like @earshinov mentioned I think this should be done from outside `angular-archwizard`. In a nutshell you need to query the size of the window and then choose the shown wizard layout accordingly. 

> #2 My second suggestion is making it scrollable as the screen size reduces we will be showing only one arch-step at a time i mean as we shoiwng it for forms one at a time.We can show one step title at a time when screen size reduces.

Can you give a short (hand drawn) example how this would like? It is hard for me to imagine what you want to do.

**Comment by madoar** [comment]
> My basic opinion is that angular-archwizard itself cannot know how the library user would like to structure the page. Even if angular-archwizard comes up with some solution, chances are that this solution will suit some users, but not others.

> I would leave solving this problem to the library user (probably with help of custom styles as you demonstrated).

Yes, I tend to agree. I'm not against adding support for mobile devices. I think that mobile devices should be supported by providing a dedicated style, everything else (i.e. applying said style) should be done by the user of the library according to his own criteria. 

The main issue for me is that I have no idea how a wizard should look on a mobile device with limited screen space. If someone has a good idea how a wizard should/could look on a mobile devices don't hesitate to tell us, ideally with a prototype of the corresponding layout. If it is good I don't see an argument against adding it.

**Comment by gauravmasand09** [comment]
I have fixed it by making the text as display none for smaller screens , below is ths code you can have a look


@media (max-width:320px)  { 
    aw-wizard ::ng-deep .horizontal ul.steps-indicator li a .label{
        display: none;
    }
}
@media (max-width:481px)  {
    aw-wizard ::ng-deep .horizontal ul.steps-indicator li a .label{
        display: none;
    }
 }
@media (max-width:641px)  { 
   aw-wizard ::ng-deep .horizontal ul.steps-indicator li a .label{
    display: none;
    }
 }

**Comment by madoar** [comment]
@gauravmasand09 can you by chance share a screenshot how this looks?

Additionally `::ng-deep` should not be required.
