### ISSUE TITLE
aw-wizard-step navigation Custom Symbol

### ISSUE THREAD

**Issue by sssprof** [madoar/angular-archwizard#250]
**Custom Navigation symbol not displaying.**

<aw-wizard> 
<aw-wizard-step stepTitle="Select Student" [navigationSymbol]="{ symbol: '&#xf2b9;' }">
My contents 
</aw-wizard-step>
</aw-wizard>

**Comment by madoar** [comment]
Please provide more information otherwise I'm unable to help

**Comment by sssprof** [comment]
Code I have used as below

```
<aw-wizard navBarLayout="large-empty-symbols">
      <aw-wizard-step stepTitle="Select Experience" [navigationSymbol]="{ symbol: '&#xf2b9;' }">

</aw-wizard-step>
 </aw-wizard>
```

[navigationSymbol]="{ symbol: '&#xf2b9;' }" = is not showing symbol, its showing blank.

**Comment by madoar** [comment]
From which font is the symbol? Did you by any chance update some other dependency during that time when your application began to not work as intended? 

I think it is unlikely that the application "just broke" after a certain time until which it was working perfectly fine. I think it is likely that something else in your environment changed that broke it.

**Comment by madoar** [comment]
I think this issue has been solved. If this should not be the case please open a new issue.
