### ISSUE TITLE
Conditional [navigationSymbol]

### ISSUE THREAD

**Issue by tmlinc** [madoar/angular-archwizard#251]
Excellent work on the wizard!!

Just wanted to know if it's possible to change the symbol based on the step-indicator parent CSS class.

Right now, I'm using numbers as my symbol on each step, but when the step element receives the 'complete' class, I would like to change the symbol to a FontAwesome checkmark.

**Comment by madoar** [comment]
The step symbol is not set via css. It is set using a separate html element:

https://github.com/madoar/angular-archwizard/blob/ce015340584492e15e38383a2f3b1cbe0d7981fb/src/lib/components/wizard-navigation-bar.component.html#L16-L19

Currently we don't provide a public method to query a wizard which steps have been completed.
In theory you could use the `WizardComponent#getStepAtIndex` method to query a `WizardStep` and then ask it whether it has been completed by calling `WizardStep#completed`. This value can then be used to set specify the step symbol of the step by using the [`[awWizardStepSymbol]`](https://github.com/madoar/angular-archwizard#awwizardstepsymbol) directive.

The issue with this solution is that it uses an internal API to access the state of a wizard step which bears a certain risk when updating the version of `angular-archwizard`. @earshinov I think it may be a good idea to provide an official mechanism to "inject" the state of a step into the wizard step so that it can be used from inside the step. What do you think about this?

**Comment by earshinov** [comment]
> @earshinov I think it may be a good idea to provide an official mechanism to "inject" the state of a step into the wizard step so that it can be used from inside the step. What do you think about this?

It looks useful.

As a workaround, you can wrap step contents in an Angular component and inject the `WizardStep` into it (demo: https://angular-archwizard-step-injection.stackblitz.io).

A better approach would probably be to allow the user to pass an angular template ref to `<aw-wizard-step template="..."></aw-wizard-step> and pass the wizard step through template context. In this case the user will not need to create a separate component. Instead, they will only need to define a template like this:

```
<ng-template #stepOne let-wizardStep="wizardStep">
  {{wizardStep.stepTitle}}: {{wizardStep.completed}}
</ng-template>
```

I will come up with a demo later this week.

By the way, the `WizardStep` interface is already part of the API (https://github.com/madoar/angular-archwizard/blob/develop/src/index.ts), so it should be relatively safe to use it.

**Comment by earshinov** [comment]
To solve the reporter's problem, we only need to pass wizard step through template context to the `awWizardStepSymbol` template, which will look like this:

```
<aw-wizard-step (stepEnter)="enterStep($event)">
  <ng-template awWizardStepSymbol let-wizardStep="wizardStep">
    <i *ngIf="!wizardStep.completed" class="far fa-file"></i>
    <i *ngIf="wizardStep.completed" class="far fa-check"></i>
  </ng-template>
</aw-wizard-step>
```

**Comment by tmlinc** [comment]
@earshinov this looks like a great idea!  Any idea on how long it would take to add this enhancement?

**Comment by earshinov** [comment]
So far it seems pretty simple and straight-forward, but there is always a chance that some difficulties arise in the process. About time estimation, @madoar will answer better, because I am currently short of time to contribute to archwizard…

**Comment by tmlinc** [comment]
Okay...I look forward to the enhancement.

**Comment by madoar** [comment]
> By the way, the WizardStep interface is already part of the API (https://github.com/madoar/angular-archwizard/blob/develop/src/index.ts), so it should be relatively safe to use it.

Yes `WizardStep` is indeed stable, but I don't think `WizardComponent#getStepAtIndex` can be considered stable. In my opinion this method is for internal use.

> As a workaround, you can already wrap step contents in an Angular component and inject the WizardStep into it (demo for angular-archwizard@5.0.0: https://angular-archwizard-step-injection.stackblitz.io).

I think you mean something like:

Template:
```html
<aw-wizard-step #wizardStep1 ...>
   ...
</aw-wizard-step>
```

Component:
```typescript
@ViewChild('wizardStep1')
public wizardStep1: WizardStep;

...
```
right?

This is indeed better than using `WizardComponent#getStepAtIndex`!

> A better approach would probably be to allow the user to pass an angular template ref to aw-wizard-step and receive the wizard step through template context. In this case the user will not need to create a separate component.

To allow this we will only need to add `[ngTemplateOutletContext]="{wizardStep: step}"` to the `ng-container` definitions in https://github.com/madoar/angular-archwizard/blob/ce015340584492e15e38383a2f3b1cbe0d7981fb/src/lib/components/wizard-navigation-bar.component.html#L11-L20 right?

> @earshinov this looks like a great idea! Any idea on how long it would take to add this enhancement?

If my above assumptions are correct I think the necessary changes will be quite easy to make. The difficult parts are:
- updating the documentation
- updating the tests / adding additional tests
- adding an example how to use this to the demo/example repository

I think I will have some time to work on this (and other issues as well) starting next week. I'm currently planning to have the next release some time after the Angular 9 release which should be soon.

**Comment by tmlinc** [comment]
Thanks for the update!

**Comment by earshinov** [comment]
> I think you mean something like:
> 
> Template:
> 
> <aw-wizard-step #wizardStep1 ...>
>    ...
> </aw-wizard-step>
> Component:
> 
> @ViewChild('wizardStep1')
> public wizardStep1: WizardStep;
> 
> ...
> right?

If the goal is to access a `WizardStep` in the component where the wizard is defined, then yes.

> To allow this we will only need to add [ngTemplateOutletContext]="{wizardStep: step}" to the ng-container definitions

Yes, I think that's all we need 👍
