### ISSUE TITLE
goToStep not executing 

### ISSUE THREAD

**Issue by AbhijitMuke** [madoar/angular-archwizard#256]
First of all, thanks to you for building this awesome library with angular.

I am using `angular-archwizard 5.0.0` with` Angular 5.2.4`. My application has some different requirements, where I want to jump into previous state of the form. It means, for editing records second time user will jump to previous form step where he was. I want mark sure that, when user is jumping to specific form, want to mark the previous steps as completed.

For above purpose, I started using `goToStep()` method with destination index of step, but didn't had success. Figuring out, how can I mark completed the previous steps and jump into specific step. Need your quick help.

Thanks in advance.

**Comment by madoar** [comment]
I'm not sure I understand completely what you want to do. If I understand you correctly you want to be able to move from a given step, e.g. step 1, to a later one, e.g. 4. During this navigation all steps that are located in-between, e.g. step 1, step 2 and 3 should be marked as completed?

If this is indeed what you want to do then I can think of three solutions:
1) You provide your own implementation of a `navigation mode` that supports such a navigation. An example how this can be done can be found [here](https://github.com/madoar/angular-archwizard-demo/tree/develop/src/app/custom-navigation-mode)
2) Another option is to split your navigation in multiple valid navigations. This can be realized by using `goToNextStep()` multiple times
3) A third solution would be to mark all steps that can be skipped with `awOptionalStep`

**Comment by madoar** [comment]
I think this issue has been solved. If this should not be the case please open a new issue.
