### ISSUE TITLE
Hide step titles

### ISSUE THREAD

**Issue by paulsperanza** [madoar/angular-archwizard#258]
Can I hide the step titles?

**Comment by madoar** [comment]
Yes you can. The method to do so depends on how you specify your step titles:
- if you use `[stepTitle]` you can use an `if` condition to return `""` if you don't want to show a step title
- if you use `[awWizardStepTitle]` you can again use an `if` condition to return `""` in case you don't want to show a step title.
- a third method is to read the step title from a method where you again have full control when to return a step title.

**Comment by madoar** [comment]
I think this issue has been solved. If this should not be the case please open a new issue.
