### ISSUE TITLE
Step becomes non-clickable after adding some html to it

### ISSUE THREAD

**Issue by Gevko** [madoar/angular-archwizard#261]
Hello!

I am having an issue, I need to inform the user after he completes the wizard with errors, in which step the error was made, so I add a icon to the step.

I am getting the step html element by the stepId, and so I add some inner HTML to the step html element. After I do it, I can not navigate to the step clicking the step icon. 

This behaviour is kinda required and necessary, but maybe i am not doing it the correct way. Could you advise me how to it right?

Thanks.

**Comment by madoar** [comment]
How are you changing the navigation icons? Does your browser show some error message in the debug terminal? Can you provide a short example application that produces your error?

**Comment by Gevko** [comment]
`				const stepElmnt = document.getElementById('stepId');

				stepElmnt.innerHTML += '<div class="dot"><div class="fas fa-exclamation-circle fa-lg"></div></div>';
					`

I do this way.

**Comment by madoar** [comment]
Please provide a short example application that produces the issue. A snipped like you have provided does not allow me to reproduce your issue.

Based on what you have provided I would suggest you to try the [`[awWizardStepTitle]`](https://github.com/madoar/angular-archwizard#awwizardsteptitle) and [`[awWizardStepSymbol]`](https://github.com/madoar/angular-archwizard#awwizardstepsymbol). These directives allow you to set the title and navigation icon based on the current state of your model.

**Comment by Gevko** [comment]
On this sample you can reproduce the error. Just do npm i and ng serve and click on the button. 
On the 3rd step, the button adds some html to the 1st step, and after that it is impossible to navigate there if clicking on the step's icon. But still, you can navigate to the 2nd step (that has not any added html).

https://wetransfer.com/downloads/8fcc5c0f207af587db67c377822ae0f820200213152059/4fc86c67577ec79251fc94c9a49eca2220200213152059/718f70

**Comment by madoar** [comment]
Try:

### app.component.ts

```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  public title = 'wizard-demo';

  public modifyIcon = false;

  addStepIcon() {
    this.modifyIcon = true; 
  } 
}
```

### app.component.html

```html
<aw-wizard [navBarLayout]="'large-empty-symbols'">

  <aw-wizard-step [stepId]="'stepId1'" [stepTitle]="'step1'" [navigationSymbol]="{ symbol: '1' }">
    <ng-template awWizardStepSymbol>
      1<i *ngIf="modifyIcon" class="fas fa-exclamation-circle fa-lg"></i>
    </ng-template>

    some content

    <button type="button" [awGoToStep]="{ stepId: 'stepId2' }">Next</button>
  </aw-wizard-step>

  <aw-wizard-step [stepId]="'stepId2'" [stepTitle]="'step2'" [navigationSymbol]="{ symbol: '2' }">
    some content
    <button type="button" [awGoToStep]="{ stepId: 'stepId3' }">Next</button>
  </aw-wizard-step>

  <aw-wizard-step [stepId]="'stepId3'" [stepTitle]="'step3'" [navigationSymbol]="{ symbol: '3' }">
    some content
    <button type="button" (click)="addStepIcon()">Change Icon</button>
  </aw-wizard-step>

</aw-wizard>
```

Please be aware that depending on what you want to add to the navigation icon you may want to modify its style as well, otherwise a linebreak could be inserted.

**Comment by madoar** [comment]
I think this issue has been solved. If this should not be the case please open a new issue.
