### ISSUE TITLE
Angular 9

### ISSUE THREAD

**Issue by achimha** [madoar/angular-archwizard#270]
Hi,

when do you plan to release the fix for Angular 9?

Thanks!

**Comment by madoar** [comment]
@achimha thank you for your interest in the next release! I currently plan to release the next version of `angular-archwizard` either during the next week or the week after. 

The reason for the delay is that I still want to do some small improvements to the tests and some small changes to the demo before releasing both the library and the demo together. More specific I plan to perform the following changes before releasing:
- change the test description name in
   https://github.com/madoar/angular-archwizard/blob/6e1fe5050bb1514fa1ebb58ee83c17ccb702f80a/src/lib/components/wizard.component-nested-steps.spec.ts#L28
- test whether the correct step objects were loaded in
   https://github.com/madoar/angular-archwizard/blob/6e1fe5050bb1514fa1ebb58ee83c17ccb702f80a/src/lib/components/wizard.component-nested-steps.spec.ts#L58-L60
- set some expected content (like step titles and step content) in
   https://github.com/madoar/angular-archwizard/blob/6e1fe5050bb1514fa1ebb58ee83c17ccb702f80a/src/lib/components/wizard.component-nested-steps.spec.ts#L9-L21
- add an example for #253 to the demo repository
- add an example for #254 to the demo repository
- add an example for #252 to the demo repository
- add a link to gitpod to the demo repository

Help is always welcome :)

**Comment by madoar** [comment]
I have released version `6.0.0` of `angular-archwizard` today! This version is built using Angular 9. If you discover any issues feel free to open a new issue.
