### ISSUE TITLE
CSS for element div with class wizard-steps

### ISSUE THREAD

**Issue by ifritmitsuma** [madoar/angular-archwizard#289]
I'm trying to customize the element div with class wizard-steps that is compiled, but for some reason my css rules for that element disappear when rendering. It seems this element does not inherit the _ngcontent-<generated-id> attribute, could that be the issue?

**Comment by madoar** [comment]
Can you please provide an example of what exactly you are trying to do?

**Comment by madoar** [comment]
If you continue to face this issue feel free to open a new issue
