### ISSUE TITLE
On MS Edge the wizard step2 content is not displayed until I click on DOM

### ISSUE THREAD

**Issue by sergiu79** [madoar/angular-archwizard#29]

**Comment by madoar** [comment]
Hmm, can you please post a screenshot and maybe a short code example, that produces this error for you? In addition it would be helpful to know your browser version. I guess you're using windows 10?

**Comment by sergiu79** [comment]
`<div class="wizard-steps horizontal" _ngcontent-c0="">
      
            <wizard-step hidden="" _nghost-c1="">
    
                <div class="container">
   
                    <div class="buttons">
                        <button class="pat-button default next" nextStep="">
                            Volgende
                        </button>
                    </div>
                </div>
            
  </wizard-step>
            <wizard-step _nghost-c1="">
    
                <div class="container">
                       
                        
                      Some text
                    <div class="buttons">
                        <button class="pat-button close-panel" previousStep="">
                            Terug
                        </button>
                        <button disabled="" class="pat-button default next" nextStep="">
                            Volgende
                        </button>
                    </div>
                </div>
            
  </wizard-step>
            <wizard-step hidden="" _nghost-c1="">
    
                <div class="container">
                    <div class="buttons">
                        <button class="pat-button close-panel" previousStep="">
                            Terug
                        </button>
                        <button class="pat-button default next" nextStep="">
                            Volgende
                        </button>
                    </div>
                </div>
            
  </wizard-step>
            <wizard-step hidden="" _nghost-c1="">
    
                <div class="container">
                    <div class="buttons">
                        <button class="pat-button close-panel" previousStep="">
                            Terug
                        </button>
                        <button class="pat-button default next">
                            Klaar
                        </button>
                    </div>
                </div>
            
  </wizard-step>
        
    </div>`

**Comment by sergiu79** [comment]
![image](https://user-images.githubusercontent.com/5412287/30158500-c9053ac8-93c5-11e7-8fed-c7b2d5c238e5.png)
 Step 2 after clicking next on step 1

**Comment by sergiu79** [comment]
![image](https://user-images.githubusercontent.com/5412287/30158556-eca17aaa-93c5-11e7-9d0a-1e683f84398e.png)
Step 2 after clicking on DOM (anywhere)

**Comment by sergiu79** [comment]
I suspect is some CSS height property or maybe some Angular related issue or something should be done somewhere on ngOnInit

**Comment by sergiu79** [comment]
Yes, I am on Windows 10 , Edge browser.
For other browsers, including the IE 11, it works

**Comment by sergiu79** [comment]
I know Edge sucks

**Comment by madoar** [comment]
I see, that you've changed the navigation bar layout/design.
Can you please test if the default layouts, i.e. the ones provided directly by `ng2-archwizard` work correctly?

In addition:
I like your layout/design! If you're interested, we could add it to `ng2-archwizard` directly.

**Comment by sergiu79** [comment]
On Chrome/ other browsers looks like this:
![image](https://user-images.githubusercontent.com/5412287/30159268-4ab85760-93c8-11e7-8ac1-46fdef892e09.png)
I had to add a little patch to have the same distance in IE between step indicators

**Comment by sergiu79** [comment]
I think in  Edge the `hidden` attribute is not adjusting properly

**Comment by sergiu79** [comment]
It is kind of hard for me to test now the original implementation because on my remotely dev machine I have Window Server 2012 with IE 11 and the screenshots are from a test environment where I don't have access to publish at this moment, kind of hard to explain either

**Comment by madoar** [comment]
Does Edge show the official demo (https://madoar.github.io/ng2-archwizard-demo/#/navigation-symbol/custom) correctly?

**Comment by madoar** [comment]
@sergiu79 did you have some success during your search for the error? 
Sorry that I can't help you much here, but I'm working and linux and therefore I'm currently unable to test it on any windows browser.

**Comment by madoar** [comment]
This issue is quite old. If the issue still exists in `angular-archwizard` version `4.0.0` please open a new issue.
