### ISSUE TITLE
How to handle go to next step in code ?

### ISSUE THREAD

**Issue by KOSSOKO** [madoar/angular-archwizard#296]
Hello, I'm new with angular and this plugin. I used to create a normal form in <form> and get values when submit button is clicked.

With this plugin, I have this example:
```
<h5 class="mb-4">{{ 'wizard.last-end' | translate }}</h5>
<div class="card mb-5">
  <div class="card-body">
    <aw-wizard >
      <aw-wizard-step stepTitle="{{ 'wizard.step-name-1' | translate }}" style="min-height: 120px;">
        <div class="form-group">
          <label>{{ 'forms.name' | translate }}</label>
          <input type="text" class="form-control" name="name">
        </div>
        <div class="text-center">
          <button type="button" class="btn btn-primary" awPreviousStep disabled>{{ 'wizard.prev' | translate }}</button>{{" "}}
          <button type="button" class="btn btn-primary" awNextStep>{{ 'wizard.next' | translate }}</button>
        </div>
      </aw-wizard-step>
      <aw-wizard-step stepTitle="{{ 'wizard.step-name-2' | translate }}" style="min-height: 120px;">
        <div class="form-group">
          <label>{{ 'forms.email' | translate }}</label>
          <input type="text" class="form-control" name="email">
        </div>
        <div class="text-center">
          <button type="button" class="btn btn-primary" awPreviousStep>{{ 'wizard.prev' | translate }}</button>{{" "}}
          <button type="button" class="btn btn-primary" awNextStep>{{ 'wizard.next' | translate }}</button>
        </div>
      </aw-wizard-step>
      <aw-wizard-step stepTitle="{{ 'wizard.step-name-3' | translate }}" style="min-height: 120px;">
        <div class="form-group">
          <label>{{ 'forms.password' | translate }}</label>
          <input type="password" class="form-control" name="password">
        </div>
        <div class="text-center">
          <button type="button" class="btn btn-primary" awPreviousStep>{{ 'wizard.prev' | translate }}</button>{{" "}}
          <button type="button" class="btn btn-primary" awNextStep>{{ 'wizard.next' | translate }}</button>
        </div>
      </aw-wizard-step>
      <aw-wizard-completion-step stepTitle="{{ 'wizard.done' | translate }}" style="min-height: 120px;">
        <div class="text-center complete-message-centered">
          <h2 class="mb-2">{{ 'wizard.content-thanks' | translate }}</h2>
          <p>{{ 'wizard.registered' | translate }}</p>
        </div>
      </aw-wizard-completion-step>
    </aw-wizard >
  </div>
</div>
```
1- In my component class, how could I get the value of the input "name" for example in a function let's call it createCompany ?
 
2- When I click next, the next button must call createCompany, and get all values. Then I call the back end to create companyand get the response. Is it possible, to go to next only after getting the answer from my back end ? For example if the answer is 200, I go to the next step. Otherwise, I show an error message in alert.

Thanks in advance for your answer.

**Comment by madoar** [comment]
> 1- In my component class, how could I get the value of the input "name" for example in a function let's call it createCompany ?

I would suggest you to bind the value of your `name` input to a field inside your component class. You can then access this field from inside your `createCompany` function.

> 2- When I click next, the next button must call `createCompany`, and get all values. Then I call the back end to create companyand get the response. Is it possible, to go to next only after getting the answer from my back end ? For example if the answer is 200, I go to the next step. Otherwise, I show an error message in alert.

The challenge with using a backend to decide whether a wizard step can be exited is that the communication between your Angular application and your backend is asynchronous in nature. This means that when a user clicks on the `next` button that leads to the backend call it may take a certain time until the backend responses. In addition it is often unclear how the frontend should react if the backend returns a negative response.

If these points are no issues for you then I think you can make use of the `[canExit]` and `[canEnter]` inputs of the wizard steps. The `[canExit]` and `[canEnter]` inputs accept a function with the signature `function(MovingDirection): Promise<boolean>` that is called whenever the step is exited or entered.

The content of the resulting `Promise<boolean>` object is used to decide whether the step is exited or entered. In your case you could pass a function to the `[canExit]` input that performs the backend request and returns the resulting `Promise<boolean>` with the answer from your backend. For a generic example about how to use the `[canExit]` input please see [here](https://github.com/madoar/angular-archwizard-demo/tree/develop/src/app/can-exit-event). Information about the supported input types for the `[canExit]` input can be found [here](https://github.com/madoar/angular-archwizard#canexit).

**Comment by KOSSOKO** [comment]
Thanks a lot for your answer. I finally find a solution without using canExit but doing everything from code. Thanks
```
import { WizardComponent} from 'angular-archwizard';
@ViewChild(WizardComponent)  public wizard: WizardComponent;
this.wizard.goToStep(2);
```
