### ISSUE TITLE
I want to mark step as completed in arch wizard after moving to the next step.

### ISSUE THREAD

**Issue by gauravsingh0888** [madoar/angular-archwizard#298]

**Comment by madoar** [comment]
`angular-archwizard` automatically marks a step as completed when exiting it. If you want to mark other steps as completed you can either use the [`awCompletedStep` directive](https://github.com/madoar/angular-archwizard#awcompletedstep) or access the internal API of the wizard.

**Comment by madoar** [comment]
If you continue to face this issue feel free to open a new issue
