### ISSUE TITLE
Conditional Forward Navigation Mode

### ISSUE THREAD

**Issue by shinchan305** [madoar/angular-archwizard#304]
Hello,

I am using this library at multiple places in my project. At all the places, my requirement is when a step is already completed(like in edit mode), then the user should be allowed to forward/backward navigate to the steps that have already been completed.

For example, if I have 4 steps out of which 1, 2 & 3 are already completed, then I should be able to navigate to step 2 & 3 freely.

Can we have Angular's (click) event enabled on different steps of archwizard which will pass the index id of the step which is being clicked upon?

Or is there any other way we can achieve this?

**Comment by madoar** [comment]
> For example, if I have 4 steps out of which 1, 2 & 3 are already completed, then I should be able to navigate to step 2 & 3 freely.

In which step is the user currently?  

> Can we have Angular's (click) event enabled on different steps of archwizard which will pass the index id of the step which is being clicked upon?
> 
> Or is there any other way we can achieve this?

This sounds a bit like you want to configure the navigation mode to allow navigating to already visited steps in forward direction? If this is indeed the case then you may want to look [here](https://madoar.github.io/angular-archwizard-demo/#/navigation-mode/configurable) and [here](https://github.com/madoar/angular-archwizard-demo/tree/develop/src/app/configurable-navigation-mode) for an example.

If this is not the case you may want to take a look at the `[canEnter]` and `[canExit]` input parameters of the `aw-wizard-step` component. These inputs allow you to specify whether a specific step can be entered or left in a certain direction. By combining both inputs you are able to implement very complex navigation scenarios.

**Comment by shinchan305** [comment]
`In which step is the user currently?`
The user can be in any step. For example, if the user is in 1st step, 2nd & 3rd should be accessed freely. If user is in 2nd step, he should be able to jump to 1st or 3rd step.

`This sounds a bit like you want to configure the navigation mode to allow navigating to already visited steps in forward direction? If this is indeed the case then you may want to look here and here for an example.`

Yes, this one is already implemented. User can navigate to the visited steps. But like I mentioned, while editing, user starts from the 1st step and should be able to navigate to all the steps that were completed previously (in this example, step 2 & 3)

`If this is not the case you may want to take a look at the [canEnter] and [canExit] input parameters of the aw-wizard-step component. These inputs allow you to specify whether a specific step can be entered or left in a certain direction. By combining both inputs you are able to implement very complex navigation scenarios.`

I tried using [canEnter] and [canExit] input parameters but apparently, those work with the button clicks, not with the step clicks. I need the steps of wizard to be clickable.

**Comment by madoar** [comment]
> `This sounds a bit like you want to configure the navigation mode to allow navigating to already visited steps in forward direction? If this is indeed the case then you may want to look here and here for an example.`
> 
> Yes, this one is already implemented. User can navigate to the visited steps. But like I mentioned, while editing, user starts from the 1st step and should be able to navigate to all the steps that were completed previously (in this example, step 2 & 3)

For the navigation mode implementation a `visited` step is a completed step. I think it should fulfill your requirements. If you want to be able to navigate to a previously not entered step (which is therefore also incomplete) then you need to define it as complete using either the internal API or by using the [`[awCompletedStep]` directive](https://github.com/madoar/angular-archwizard#awcompletedstep). This directive allows you to define a step as completed after initialization. It accepts a condition as its input that allow for more complex activation logic.

> I tried using [canEnter] and [canExit] input parameters but apparently, those work with the button clicks, not with the step clicks. I need the steps of wizard to be clickable.

If this is the case you can make the step clickable by setting them as `optional` steps using the [`[awOptionalStep]` directive](https://github.com/madoar/angular-archwizard#awoptionalstep). This will allow the user to enter the step from basically anywhere. If you want to limit this you need to use `[canEnter]` and `[canExit]`.

**Comment by shinchan305** [comment]
![image](https://user-images.githubusercontent.com/48820791/87256317-97b5f900-c44e-11ea-8672-760fbd0ac4c9.png)
`For the navigation mode implementation a visited step is a completed step. I think it should fulfill your requirements. If you want to be able to navigate to a previously not entered step (which is therefore also incomplete) then you need to define it as complete using either the internal API or by using the [awCompletedStep] directive. This directive allows you to define a step as completed after initialization. It accepts a condition as its input that allow for more complex activation logic.`

I have attached an image of the code. I am already using the [awCompletedStep] directive, which marks my visited steps as green (which is good) and I thought it will make my steps clickable as well, but it didn't.

`If this is the case you can make the step clickable by setting them as optional steps using the [awOptionalStep] directive. This will allow the user to enter the step from basically anywhere. If you want to limit this you need to use [canEnter] and [canExit].`

Now I tried to make the steps optional as you suggested by putting the same condition which mark them completed. But again, my steps are not clickable.

As you can see in the code snippet, I am using the same condition for completion and optional. Completion works, but optional doesn't.

Is there something wrong with my code?

**Comment by madoar** [comment]
Both `awCompletedStep` and `awOptionalStep` are meant to be used in a static way. This means that the condition you are binding the both directives should not change later on. If I look at your snippet the conditions flip depending on which step (i.e. `currentStep.id`) the user is in, right?

> Is there something wrong with my code?

To be able to do a more in-depth analysis of whether there is something wrong either with the wizard or your usage of it I need an example project that allows me to test your scenario. Can you please provide such a project?

**Comment by shinchan305** [comment]
`Both awCompletedStep and awOptionalStep are meant to be used in a static way. This means that the condition you are binding the both directives should not change later on. If I look at your snippet the conditions flip depending on which step (i.e. currentStep.id) the user is in, right?`
It's not current step, it's status which I am setting before loading the archwizard component. That is the reason I am lost what is going wrong.

**Comment by sekhar679** [comment]
If this is the case you can make the step clickable by setting them as optional steps using the [awOptionalStep] directive. This will allow the user to enter the step from basically anywhere. If you want to limit this you need to use [canEnter] and [canExit].

Now I tried to make the steps optional as you suggested by putting the same condition which mark them completed. But again, my steps are not clickable.

As you can see in the code snippet, I am using the same condition for completion and optional. Completion works, but optional doesn't.


did you find the solution for this scenario???

**Comment by madoar** [comment]
As I mentioned before please provide an example application/project that I can use to recreate your issue. Otherwise it is really difficult for me to understand what exactly you want to achieve and where the problem is located.

By default the wizard allows you to navigate to the next step only. This condition is relaxed when using `[awOptionalStep]`. When using `[awOptionalStep]` you can navigate up to the next step that is not marked with `[awOptionalStep]`. 

In addition the behaviour of the navigation bar changes depending on your navigation mode. Take a look at the examples on https://madoar.github.io/angular-archwizard-demo/#/navigation-mode/default to see how the wizard behaves by default.
If you want to allow the user to skip steps using the navigation bar you will need to set `navigateForward="allow"`, see also https://madoar.github.io/angular-archwizard-demo/#/navigation-mode/free

**Comment by madoar** [comment]
If you continue to face this issue feel free to open a new issue
