### ISSUE TITLE
Need to set free navigation mode but not working

### ISSUE THREAD

**Issue by Suhas-lab** [madoar/angular-archwizard#308]
I am using this code in my project but its not working properly. Anyone please help

<aw-wizard [navBarLayout]="'large-empty-symbols'" class="custom-styling horizontal" [awNavigationMode] [navigateBackward]="allow" [navigateForward]="allow">
            <aw-wizard-step [stepTitle]="step1" awOptionalStep >
                <div class="centered-content">
                    <div>
                        <h1>First step executed</h1>
                    </div>
                </div>
            </aw-wizard-step>
            <aw-wizard-step [stepTitle]="Step2" awOptionalStep>
                class="my-custom-css-wrapper">
                <div class="centered-content">
                    <div>
                        <h1>Second step executed</h1>
                    </div>
                </div>
            </aw-wizard-step>
</aw-wizard>

**Comment by madoar** [comment]
What exactly is not working as you expect? Your code snippet looks strange, can you please fix it otherwise it is hard to help

**Comment by Suhas-lab** [comment]
Thanks madoar for reply,
Actually i have set different types of steps using <aw-wizard> and i need to set free navigation for it. Finally i got the solution on below site where one directive is use to set free navigation for steps https://www.npmjs.com/package/angular-archwizard.
Directive is [awNavigationMode] basically its by default mode is **strict** so i have do it **free** based on my logic. Now its working.
