### ISSUE TITLE
Angular Ivy compatible issue

### ISSUE THREAD

**Issue by Rocket18** [madoar/angular-archwizard#309]
This likely means that the library (angular-archwizard) which declares ArchwizardModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

When angular-archwizard will be support Ivy???

**Comment by madoar** [comment]
What version of Angular and `angular-archwizard` are you using?

**Comment by Rocket18** [comment]
Angular 10.0.5
angular-archwizard 6.1.0 (latest)

**Comment by madoar** [comment]
I've tried building the `angular-archwizard-demo` repository with ivy enabled using `ng build --aot`. It worked for me without any issues. Both `angular-archwizard` and `angular-archwizard-demo` currently use Angular 9. Maybe it is because of a change between Angular 9 and 10?

**Comment by Rocket18** [comment]
So, i installed npm package one more time and now everything looks fine, no errors in terminal. Close  issue
