### ISSUE TITLE
step works but in vscode errors

### ISSUE THREAD

**Issue by Paul75** [madoar/angular-archwizard#310]
Hello,

I add yout project to mine to do multistep wizard : 
```
<aw-wizard [navBarLayout]="'small'" [disableNavigationBar]="false" #wizzard>
    <app-custom-step awWizardStep stepTitle="Usager">
      <app-usager-add-step1 [form]="usagerForm" (submitSucceded)="wizzard.goToNextStep()"></app-usager-add-step1>
    </app-custom-step>

    <app-custom-step awWizardStep stepTitle="Contrat">
      <app-usager-add-step2
        [form]="usagerForm"
        (backStep)="wizzard.goToPreviousStep()"
        (submitSucceded)="wizzard.goToNextStep()"
      ></app-usager-add-step2>
    </app-custom-step>

    <app-custom-step awWizardStep stepTitle="Contacts">
      <app-usager-add-step3
        [form]="usagerForm"
        (backStep)="wizzard.goToPreviousStep()"
        (submitSucceded)="wizzard.goToNextStep()"
      ></app-usager-add-step3>
    </app-custom-step>

    <app-custom-step awWizardStep stepTitle="Information">
      <app-usager-add-step4
        [form]="usagerForm"
        (backStep)="wizzard.goToPreviousStep()"
        (submitSucceded)="onFormSubmit()"
      ></app-usager-add-step4>
    </app-custom-step>
</aw-wizard>
```

It works but in my VSCODE I have this errors on app-custom-step : 

```
'app-usager-add-step1' is not a known element:
1. If 'app-usager-add-step1' is an Angular component, then verify that it is part of this module.
2. If 'app-usager-add-step1' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.ng
```

thanks

**Comment by madoar** [comment]
This looks like there is a problem with your `app-usager-add-step1` component. Maybe you forgot to declare it in a `@NgModule` directive of your application?

**Comment by Paul75** [comment]
Hello,

Not it declared....

I solved to change : 

`<app-custom-step awWizardStep ... >`

to : 

`<aw-wizard-step awWizardStep ... >`

Thanks

**Comment by madoar** [comment]
Nice to hear that you solved your issue.

In that case `awWizardStep` is redundant because it basically leads to the same result as `aw-wizard-step`. The main difference between both is that `aw-wizard-step` is a component which can be used as a wrapper for a number of other components that make up a wizard step. In comparison `awWizardStep` can be used to enhance an existing component of your application with the necessary functionality to be a wizard step that can be processed by `angular-archwizard`.
