### ISSUE TITLE
Step icon stacks when step count is more than 10

### ISSUE THREAD

**Issue by DemiRamiro** [madoar/angular-archwizard#311]
Hi.

I am just using archwizard now,

I found this issue when I put more than 10 steps.

![image](https://user-images.githubusercontent.com/13651932/92329697-b2e26500-f09b-11ea-9a69-dca71c2feae4.png)

When it is just 10 it looks fine

![image](https://user-images.githubusercontent.com/13651932/92329709-cd1c4300-f09b-11ea-87dc-e779de147471.png)

**Comment by madoar** [comment]
`angular-archwizard` currently only supports Wizards with up to 10 steps.
This can be changed by modifying the upper limit of the following loop in the stylesheets:

https://github.com/madoar/angular-archwizard/blob/187cf078dd3b2d635e3bbb6256e54949d2f23934/src/css/wizard-navigation-bar.scss#L380-L391

How many steps do you require?

**Comment by madoar** [comment]
If you continue to face this issue feel free to open a new issue
