### ISSUE TITLE
Aot build issue

### ISSUE THREAD

**Issue by sfrinx** [madoar/angular-archwizard#313]
Hello,
I delevop an app with Ionic 5 (Angular 8). When i try to build with production enviroment i see this error:

ERROR in Directive WizardCompletionStep in /Users/scaminati/Documents/workspaces/github/Fait/easyfait/node_modules/angular-archwizard/angular-archwizard.d.ts has no selector, please add it!
[ng] Directive WizardStep in /Users/scaminati/Documents/workspaces/github/Fait/easyfait/node_modules/angular-archwizard/angular-archwizard.d.ts has no selector, please add it!
[ng] Cannot determine the module for class WizardCompletionStep in /Users/scaminati/Documents/workspaces/github/Fait/easyfait/node_modules/angular-archwizard/angular-archwizard.d.ts! Add WizardCompletionStep to the NgModule to fix it.
[ng] Cannot determine the module for class WizardStep in /Users/scaminati/Documents/workspaces/github/Fait/easyfait/node_modules/angular-archwizard/angular-archwizard.d.ts! Add WizardStep to the NgModule to fix it.

I fix the problem by removing "aot": true and "buildOptimizer": true, on angular build chain. But i don't want to remove this.

Could you add support for aot?

Thanks a lot!

**Comment by madoar** [comment]
Which version of `angular-archwizard` are you using? Please be sure to use `angular-archwizard` version `5.x.y` with Angular 8 and `angular-archwizard` version `6.x.y` with Angular 9+.

`angular-archwizard` supports `aot`, which can be tested by building the [demo repository](https://github.com/madoar/angular-archwizard-demo) using `ng build --aot`. The selector change for directives is quite new in Angular. I think it was introduced in Angular 9, see also [here](https://angular.io/guide/migration-undecorated-classes#im-a-library-author-should-i-add-the-directive-decorator-to-base-classes), therefore it is necessary to use a different version of `angular-archwizard` depending on your used Angular version.

**Comment by sfrinx** [comment]
Ok thank you now it work. I suggest you to put this information (version 5 for angular 8) in the main page of the repository.
