### ISSUE TITLE
Problems creating dynamic components in aw-wizard-step

### ISSUE THREAD

**Issue by rikimm** [madoar/angular-archwizard#316]
As the title says, I am trying to create dynamic components within an aw-wizard-step, I have the following code
HTML:

```

<aw-wizard [navBarLocation]="'left'" [disableNavigationBar]="false" >
    <aw-wizard-step stepTitle=""  #billingComponent [stepId]="3" (stepEnter)="function($event)">
    </aw-wizard-step>
</aw-wizard>

```
Component.ts:

```
import { WizardBillingComponent } from '../components/wizard-billing/wizard-billing.component';

@ViewChild('billingComponent', { read: ViewContainerRef }) billing: ViewContainerRef;

 constructor(private factoryResolve: ComponentFactoryResolver){}

  function(event) {
    const factory = this.factoryResolve.resolveComponentFactory(WizardBillingComponent);
    this.componentRef = this.billing.createComponent(factory);
  }
```

the part of the html of the component that I am sending to call is not shown, what if you notice is that all the functions or inputs of the component are shown in the console.log

**Comment by madoar** [comment]
Your code snippet is missing the information what you are doing with `componentRef`. It only assigns a value to it but does not seem to access it afterwards? Can you please provide an example project that illustrates what exactly you are trying to do and what does not work?

**Comment by madoar** [comment]
If you continue to face this issue feel free to open a new issue
