### ISSUE TITLE
Can't click a button added to a Step Title to perform a certain action

### ISSUE THREAD

**Issue by NA-Jalilius** [madoar/angular-archwizard#336]
Hello @madoar , 
I'm trying to add a button to the step title of the wizard, in order to delete this step on button click, but can't get it to be clicked, it's like if it's disabled with all the navigation bar for which I disabled the navigation with `[disableNavigationBar]="true"`, but if I set it to `false` the click start to be intercepted by the step header instead of the button

This is my code snippet :

`<html></html>

      <aw-wizard navBarLayout="large-empty-symbols" [disableNavigationBar]="true">

        
        <aw-wizard-step [awNavigationMode] navigateForward="visited" [navigationSymbol]="{ symbol: (i+1).toString() }"
                        (stepEnter)="changeHelpPannelContent(i); sendFormValidationRequest(i - 1);"
                        *ngFor="let wizardStep of wizardSteps; let i = index; let first = first; let last = last">

          <ng-template awWizardStepTitle>
            <span class="d-none d-md-block">{{wizardStep?.header}} <button class="btn btn-light" *ngIf="wizardSteps?.length > 3 && i > 1" (click)="deleteStepFromWizard(i);"><i class="icon-bin2 text-danger"></i></button></span>
            <span class="d-md-none">{{wizardStep?.header_sm}} <button class="cursor-pointer" *ngIf="wizardSteps?.length > 3 && i > 1" (click)="deleteStepFromWizard(i);"><i class="icon-bin2 text-danger"></i></button></span>

          </ng-template>
        </aw-wizard-step>
        

      </aw-wizard>
      `

Please could you correct me if I'm missing something regarding the Wizard usage logic heare ?
PS : I'm on Angular 8 with `"angular-archwizard": "^5.0.1"`

**Comment by madoar** [comment]
The step titles inside the navigation bar are not meant to contain (additional) buttons.
The titles themselves function as links, which can be clicked on to navigate to the step when certain conditions are fulfilled.
These conditions can be defined by using a navigation mode and by specifying `[canEnter]` and/or `[canExit]` of your wizard steps.

Otherwise you are free to add buttons to the content section of your wizard steps.

**Comment by NA-Jalilius** [comment]
Hello @madoar,
Alright, I see what you're saying. Thanks for the response.
Exactly, as you mentioned and as I've thought of, the solution is to add the button in the content area and play the gymnastic using services etc ...
Thanks again my friend !
Closing the issue ...
