### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by achimha** [madoar/angular-archwizard#52]
ng2-archwizard is not really a suitable name anymore as it targets Angular 4 and there will soon be Angular 4.

What about ngx-archwizard or ng-archwizard? Both are available in npm.

The upcoming 2.0 would be a good opportunity to make this change.

**Comment by madoar** [comment]
`ngx-archwizard` seems to be already taken in npm (https://www.npmjs.com/package/ngx-archwizard).
I've thought about using `angular-archwizard`, but `ng-archwizard` would be a possibility too, what do you think is better?

Off-topic: I've released version 2.0.0 on npm two days ago, I just haven't had the time to add a new release to the github project yet.

**Comment by achimha** [comment]
I have no real preference, angular-* is found often (it used to be associated with Angular 1.x but now it's popular for Angular >= 2 projects) and ng-* is frequent as well.

**Comment by domrich** [comment]
"furqanaziz published 2 months ago
0.0.1 is the latest release
github.com/madoar/ng2-archwizard
MIT" ngx-archwizard seems to be exactly your code 2 month ago. You should try to contact furqanaziz and go for that naming.

**Comment by furqanaziz** [comment]
I do have `ngx-archwizard` and just forked this repo with minor changes. If you want `ngx-archwizard` I can pass it for this great project.

**Comment by madoar** [comment]
@furqanaziz I would like that alot :+1:

**Comment by madoar** [comment]
I've good news :)
I've just release version `3.0.0` of this library under a new name: [angular-archwizard](https://github.com/madoar/angular-archwizard-demo)!
