### ISSUE TITLE
ArchWizard Documentation

### ISSUE THREAD

**Issue by LastCodeDE** [madoar/angular-archwizard#76]
I included the wizard like the example:

`import { ArchwizardModule } from 'ng2-archwizard';

@NgModule({
  imports: [
    ArchwizardModule
  ],
})
export class Module { }`

Unfortunately now is in my component.ts file no documentation to the tool included, normaly the intellisense of visual studio gives me the possible attributes and functions  of the included components.

.html file
`<wizard #wizard navBarLocation="top" navBarLayout="large-filled-symbols">`

.ts file
`    @ViewChild("wizard") wizard: ArchwizardModule;`

`import { ArchwizardModule } from 'ng2-archwizard';` gives only the Module and nothing more.

**Comment by madoar** [comment]
Hmmm, I'm not sure what needs to be done to make visual studio (and other IDEs) show the documentation for `ng2-archwizard`.
If you (or someone else) know how this can be achieved, it would be nice if you could either open a new PR containing the required changes or send me a message telling me what needs to be changed :)

**Comment by LastCodeDE** [comment]
I can not use the aot compile from angular because the archwizard haven't a documentation.

This is the error code of the aot-compiler:
`npm : client/app/shared/basic.module.ts(16,34): error TS7016: Could not find a declaration file for module 'ng2-archwizard'. 'Current.Directory()/node_modules/ng2-archwizard/index.js' implicitly has an 'any' type.`

I think you have to add a .d.ts file. I found this explaination on the web:
https://github.com/Microsoft/TypeScript/issues/8335

**Comment by madoar** [comment]
@LastCodeDE Are you using angular 5?
If yes, could you please try building the current master branch (i.e. version `5.0.0`) and see if it works?
The current master branch is using a new build system for the project.
After building the project with `npm run build`, please be sure to only add the `dist` folder to your application.

**Comment by madoar** [comment]
Please be aware that the new version contains some syntactical changes.

**Comment by LastCodeDE** [comment]
@madoar Thank you your answer.

I am using Version 2.1.0. I could not find a newer release version here. 

Will it be fixed in a newer version? 
How long do you think you need for the next release?

**Comment by madoar** [comment]
I want to have it fixed in a newer version.
The current development version is `3.0.0`, which you currently need to build yourself to use it.
I still need a few weeks, because I need to change the demo project to be compatible with the version `3.0.0`.
In addition I still want to change some small parts of the code.

As a note:
To use version `3.0.0`, I believe you'll need to use angular 5, otherwise angular may throw some version incompatibility errors.

**Comment by LastCodeDE** [comment]
Hi Madoar,

we are using now angular 5.

Unfortunately unitl yet there is no release version 3.0.0. I need this change really important. Could you tell me when you will release this version?

Regards
LastCodeDE

**Comment by madoar** [comment]
@LastCodeDE I'm working on it.
It's not much that needs to be done, until I can publish the next release.

The main things that need to be done is updating the README file and making sure that the demo contains an example for all the new features.

**Comment by madoar** [comment]
I've just released version `3.0.0` of the library.
Version `3.0.0` is released under a new package name, named [angular-archwizard](https://www.npmjs.com/package/angular-archwizard).

It would be nice if you could test if it works with the new version and tell me your findings :)

**Comment by LastCodeDE** [comment]
Now it works finde. Thank you for the work.
