### ISSUE TITLE
[help wanted] How to proceed to next step only after successful http service call / dispatched action with ngrx store

### ISSUE THREAD

**Issue by gssjr** [madoar/angular-archwizard#79]
I'm wondering if anyone can offer some suggestions on how to accomplish the following behavior:

My Wizard is a form broken up over multiple steps. There is an http service call when pressing the next button on each wizard step. I want to only proceed to the next step if the service call is successful, otherwise display the error returned by the service.

If using plain injected Angular services I imagine I can import the WizardComponent and use the navigation methods programmatically instead of using the nextStep directive.

pseudo-code:
```
onProceedToNextStep() {
    this.myService.myServiceMethod()
        .then(() => this.wizard.goToNextStep())
        .catch((err) => { this.error_message = 'There was an error: ' + err; });
}
```

Would you recommend this approach?

How would I accomplish this if I'm using ngrx store (a reactive state management system) which uses RxJS observables and triggers the service call as a side effect of a dispatched action?:

```
onProceedToNextStep() {
    this.store$.dispatch(new TriggersCallToMyServiceMethodAction());
    // I want only proceed to next step if the service called as an effect of dispatching this action returns a success, otherwise display error on current wizard step
}
```

**Comment by madoar** [comment]
@gssjr take a look at the `[canEnter]` and `[canExit]` input parameters of the `wizardStep` directive and `wizard-step` component. These parameters accept functions returning a `Promise` object.   
To convert an `Observable` to a `Promise` object, you can use the `toPromise()` function (see https://stackoverflow.com/questions/36777284/angular-2-convert-observable-to-promise).
