### ISSUE TITLE
Unable to Import ng2-archwizard

### ISSUE THREAD

**Issue by umeshka** [madoar/angular-archwizard#87]
Hi All,
i am getting below error, while using 'madoar/ng2-archwizard'. Please help me to reslove the below issue.

![image](https://user-images.githubusercontent.com/22589628/35094600-b7a98fcc-fc6b-11e7-8e72-21eebbcbeb6d.png)

![image](https://user-images.githubusercontent.com/22589628/35094228-ad749a02-fc6a-11e7-81ef-4255e71c8572.png)

![image](https://user-images.githubusercontent.com/22589628/35094256-befceedc-fc6a-11e7-8040-3d348ec7efb0.png)

Thanks and Regards,
Umesh B. K

**Comment by umeshka** [comment]
Please help on above issue.

**Comment by madoar** [comment]
@umeshka I've only used webpack before, therefore I'm not sure I can help you setting up the correct `system.js` import. 
It's possible, that version `2.1.0` needs some additional changes to make it usable with `system.js`.

I'm currently working on version `3.0.0`, which will use a new packaging library.
As far as I've read this should enable you to import `ng2-archwizard` with `system.js`.
If you want to give it a try you currently need to clone the repository and build it yourself.

**Comment by madoar** [comment]
I've just released version `3.0.0` of the library.
Version `3.0.0` is released under a new package name, named [angular-archwizard](https://www.npmjs.com/package/angular-archwizard).

Version `3.0.0` is built with `ng-packagr`, which supports system.js.
