### ISSUE TITLE
Styles are not loading properly

### ISSUE THREAD

**Issue by MorlaRamakrishna** [madoar/angular-archwizard#93]
Hi,

I have tried to use this in angular 4 application.

I have installed via  **npm install --save ng2-archwizard**

Imported in module via **import { ArchwizardModule } from 'ng2-archwizard';**

Added code in my html file like below

```
<md-card>
    <div style="height: 200px;">
        <wizard>
            <wizard-step stepTitle="Title of step 1">
                Content of Step 1
                <button type="button" nextStep>Next Step</button>
                <button type="button" goToStep="2">Go directly to third Step</button>
            </wizard-step>
            <wizard-step stepTitle="Title of step 2" optionalStep>
                Content of Step 2
                <button type="button" previousStep>Go to previous step</button>
                <button type="button" nextStep>Go to next step</button>
            </wizard-step>
            <wizard-step stepTitle="Title of step 3">
                Content of Step 3
                <button type="button" previousStep>Previous Step</button>
                <button type="button" (click)="finishFunction()">Finish</button>
            </wizard-step>
        </wizard>
    </div>
</md-card>
```
but styles are not loading properly,  output is like below
![image](https://user-images.githubusercontent.com/26458893/35220662-3a56ea26-ff9d-11e7-9fc5-040eafdbbfca.png)

But I am expecting output like below

![image](https://user-images.githubusercontent.com/26458893/35220712-63d981a6-ff9d-11e7-8cab-b6ab64bae350.png)

I don't know what I am missing here?

**Comment by madoar** [comment]
Your code creates a wizard with the [default](https://madoar.github.io/ng2-archwizard-demo/#/basic) layout.
If you want to specify symbols inside the navigation bar for your steps, you need to do two things:
1) you need to change the navigation bar layout to a layout supporting step symbols
2) you need to specify a step symbol for your steps

An example, how this can be done, can be found [here](https://github.com/madoar/ng2-archwizard-demo/tree/master/src/app/custom-step-symbol).
